import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'mm';

interface Translations {
  [key: string]: {
    en: string;
    mm: string;
  };
}

const translations: Translations = {
  // Navigation
  'nav.home': { en: 'Home', mm: 'ပင်မ' },
  'nav.about': { en: 'About Us', mm: 'ကျွန်ုပ်တို့အကြောင်း' },
  'nav.properties': { en: 'Properties', mm: 'အိမ်ခြံမြေများ' },
  'nav.companies': { en: 'Companies', mm: 'ကုမ္ပဏီများ' },
  'nav.appointments': { en: 'Appointments', mm: 'ချိန်းဆိုမှုများ' },
  'nav.postProperty': { en: 'Post Property', mm: 'အိမ်ခြံမြေတင်ရန်' },
  'nav.createListing': { en: 'Create Listing', mm: 'ပို့စ်တင်ရန်' },
  'nav.calculator': { en: 'Calculator', mm: 'တွက်ချက်စက်' },
  'nav.knowledges': { en: 'Knowledges', mm: 'သိကောင်းစရာ' },
  'nav.signIn': { en: 'Sign In', mm: 'ဝင်ရောက်ရန်' },
  'nav.signOut': { en: 'Sign Out', mm: 'ထွက်ရန်' },
  
  // Home Page
  'home.newProperties': { en: 'Find your dream property', mm: 'သင့်အိပ်မက် အိမ်ခြံမြေကိုရှာပါ' },
  'home.propertiesListed': { en: 'Properties Listed', mm: 'အိမ်ခြံမြေများတင်ထားပြီး' },
  'home.wantedListing': { en: 'Wanted Listings', mm: 'လိုချင်သောစာရင်းများ' },
  'home.citiesCovered': { en: 'Cities Covered', mm: 'မြို့များဖုံးလွှမ်းထား' },
  'home.yearsExperience': { en: 'Years Experience', mm: 'နှစ်များအတွေ့အကြုံ' },
  'home.whyChoose': { en: 'Why Choose Jade Property?', mm: 'Jade Property ကိုဘာ့ကြောင့်ရွေးချယ်ရမှာလဲ?' },
  'home.ourServices': { en: 'Our Services', mm: 'ကျွန်ုပ်တို့၏ဝန်ဆောင်မှုများ' },
  'home.getStarted': { en: 'Get Started Today', mm: 'ယနေ့စတင်ပါ' },
  'home.cta.title': { en: 'Ready to Find Your Dream Property?', mm: 'သင့်အိပ်မက်အိမ်ခြံမြေကိုရှာဖွေရန်အဆင်သင့်ဖြစ်ပြီလား?' },
  'home.cta.description': { en: 'Join thousands of satisfied clients who found their perfect property with us', mm: 'ကျွန်ုပ်တို့နှင့်အတူ သင့်အတွက်အကောင်းဆုံးအိမ်ခြံမြေကိုရှာတွေ့ခဲ့သော ကျေနပ်သောဖောက်သည်ထောင်ပေါင်းများစွာနှင့်ပါဝင်ပါ' },
  
  // Categories
  'categories.searchAllProperty': { en: 'Search All Property', mm: 'အိမ်ခြံမြေအားလုံးရှာဖွေရန်' },
  'categories.tantantan': { en: 'Tantantan', mm: 'တန်တန်တန်' },
  'categories.premiumProperties': { en: 'Premium Properties', mm: 'အဆင့်မြင့်အိမ်ခြံမြေများ' },
  'categories.preSale': { en: 'Pre-Sale', mm: 'ကြိုတင်ရောင်းချမှု' },
  'categories.installment': { en: 'Installment', mm: 'အရစ်ကျ' },
  'categories.buyerPosts': { en: 'Buyer Posts', mm: 'ဝယ်သူများ၏စာရင်း' },
  'categories.renterPosts': { en: 'Renter Posts', mm: 'ငှားသူများ၏စာရင်း' },
  'categories.vacanciesJobs': { en: 'Vacancies & Jobs', mm: 'အလုပ်လစ်လပ်မှုများနှင့်အလုပ်များ' },
  'categories.companies': { en: 'Companies', mm: 'ကုမ္ပဏီများ' },
  'categories.realEstateAgency': { en: 'Real Estate Agency', mm: 'အိမ်ခြံမြေအေဂျင်စီ' },
  'categories.constructionCompany': { en: 'Construction Company', mm: 'ဆောက်လုပ်ရေးကုမ္ပဏီ' },
  'categories.propertyManagement': { en: 'Property Management', mm: 'အိမ်ခြံမြေစီမံခန့်ခွဲမှု' },
  
  // My Wanted List
  'myWantedList.title': { en: 'My Wanted Listings', mm: 'ကျွန်ုပ်၏လိုချင်သောစာရင်းများ' },
  'myWantedList.description': { en: 'Manage your property requirements and wanted listings', mm: 'သင့်အိမ်ခြံမြေလိုအပ်ချက်များနှင့်လိုချင်သောစာရင်းများကိုစီမံခန့်ခွဲပါ' },
  'myWantedList.createNewListing': { en: 'Create New Listing', mm: 'စာရင်းအသစ်ဖန်တီးရန်' },
  'myWantedList.searchPlaceholder': { en: 'Search your listings...', mm: 'သင့်စာရင်းများကိုရှာဖွေရန်...' },
  'myWantedList.type': { en: 'Type', mm: 'အမျိုးအစား' },
  'myWantedList.allTypes': { en: 'All Types', mm: 'အမျိုးအစားအားလုံး' },
  'myWantedList.buyer': { en: 'Buyer', mm: 'ဝယ်သူ' },
  'myWantedList.renter': { en: 'Renter', mm: 'ငှားသူ' },
  'myWantedList.verificationStatus': { en: 'Verification Status', mm: 'အတည်ပြုခြင်းအခြေအနေ' },
  'myWantedList.allStatus': { en: 'All Status', mm: 'အခြေအနေအားလုံး' },
  'myWantedList.pending': { en: 'Pending', mm: 'စောင့်ဆိုင်းနေသည်' },
  'myWantedList.approved': { en: 'Approved', mm: 'အတည်ပြုပြီး' },
  'myWantedList.rejected': { en: 'Rejected', mm: 'ငြင်းပယ်ခံရသည်' },
  'myWantedList.expired': { en: 'Expired', mm: 'သက်တမ်းကုန်ဆုံးပြီး' },
  'myWantedList.property': { en: 'Property', mm: 'အိမ်ခြံမြေ' },
  'myWantedList.locationNotSpecified': { en: 'Location not specified', mm: 'တည်နေရာမဖော်ပြထား' },
  'myWantedList.budgetNotSpecified': { en: 'Budget not specified', mm: 'ဘတ်ဂျက်မဖော်ပြထား' },
  'myWantedList.beds': { en: 'Beds', mm: 'အိပ်ခန်း' },
  'myWantedList.baths': { en: 'Baths', mm: 'ရေချိုးခန်း' },
  'myWantedList.sqft': { en: 'sqft', mm: 'စတုရန်းပေ' },
  'myWantedList.posted': { en: 'Posted', mm: 'တင်ထားသည်' },
  'myWantedList.responses': { en: 'responses', mm: 'တုံ့ပြန်မှုများ' },
  'myWantedList.viewDetails': { en: 'View Details', mm: 'အသေးစိတ်ကြည့်ရန်' },
  'myWantedList.edit': { en: 'Edit', mm: 'တည်းဖြတ်ရန်' },
  'myWantedList.view': { en: 'View', mm: 'ကြည့်ရန်' },
  'myWantedList.unpublish': { en: 'Unpublish', mm: 'မထုတ်ဝေရန်' },
  'myWantedList.publish': { en: 'Publish', mm: 'ထုတ်ဝေရန်' },
  'myWantedList.delete': { en: 'Delete', mm: 'ဖျက်ရန်' },
  'myWantedList.errorLoading': { en: 'Error Loading Listings', mm: 'စာရင်းများကိုဖွင့်ရာတွင်အမှား' },
  'myWantedList.errorLoadingDesc': { en: 'There was an error loading your wanted listings. Please try again.', mm: 'သင့်လိုချင်သောစာရင်းများကိုဖွင့်ရာတွင်အမှားတစ်ခုရှိခဲ့သည်။ ကျေးဇူးပြု၍ထပ်ကြိုးစားပါ။' },
  'myWantedList.tryAgain': { en: 'Try Again', mm: 'ထပ်ကြိုးစားပါ' },
  'myWantedList.noListingsFound': { en: 'No Wanted Listings Found', mm: 'လိုချင်သောစာရင်းများမတွေ့ရှိပါ' },
  'myWantedList.noListingsMatchFilters': { en: 'No listings match your current filters.', mm: 'သင့်လက်ရှိစစ်ထုတ်မှုများနှင့်ကိုက်ညီသောစာရင်းများမရှိပါ။' },
  'myWantedList.noListingsCreated': { en: "You haven't created any wanted listings yet.", mm: 'သင့်မှာလိုချင်သောစာရင်းများမရှိသေးပါ။' },
  'myWantedList.createFirstListing': { en: 'Create Your First Listing', mm: 'သင့်ပထမဆုံးစာရင်းကိုဖန်တီးပါ' },
  
  // Create Wanted List Form
  'createWantedList.title': { en: 'Create Wanted Listing', mm: 'လိုချင်သောစာရင်းဖန်တီးရန်' },
  'createWantedList.description': { en: 'Let sellers know what you\'re looking for', mm: 'သင်ရှာဖွေနေသောအရာကိုရောင်းသူများသိစေပါ' },
  'createWantedList.loading': { en: 'Loading form data...', mm: 'ဖောင်ဒေတာများကိုဖွင့်နေသည်...' },
  'createWantedList.basicInformation': { en: 'Basic Information', mm: 'အခြေခံအချက်အလက်များ' },
  'createWantedList.preferredLocation': { en: 'Preferred Location', mm: 'နှစ်သက်သောတည်နေရာ' },
  'createWantedList.budgetPropertySpecs': { en: 'Budget & Property Specifications', mm: 'ဘတ်ဂျက်နှင့်အိမ်ခြံမြေသတ်မှတ်ချက်များ' },
  'createWantedList.contactInformation': { en: 'Contact Information', mm: 'ဆက်သွယ်ရေးအချက်အလက်များ' },
  'createWantedList.additionalRequirements': { en: 'Additional Requirements', mm: 'အပိုလိုအပ်ချက်များ' },
  'createWantedList.iAmA': { en: 'I am a', mm: 'ကျွန်ုပ်သည်' },
  'createWantedList.propertyType': { en: 'Property Type', mm: 'အိမ်ခြံမြေအမျိုးအစား' },
  'createWantedList.titleLabel': { en: 'Title', mm: 'ခေါင်းစဉ်' },
  'createWantedList.titlePlaceholder': { en: 'e.g., Looking for 3 Bedroom Apartment in Yangon', mm: 'ဥပမာ၊ ရန်ကုန်တွင်အိပ်ခန်း ၃ ခန်းပါကွန်ဒိုရှာဖွေနေသည်' },
  'createWantedList.descriptionLabel': { en: 'Description', mm: 'ဖော်ပြချက်' },
  'createWantedList.descriptionPlaceholder': { en: 'Describe what you\'re looking for in detail...', mm: 'သင်ရှာဖွေနေသောအရာကိုအသေးစိတ်ဖော်ပြပါ...' },
  'createWantedList.region': { en: 'Region', mm: 'ဒေသ' },
  'createWantedList.township': { en: 'Township', mm: 'မြို့နယ်' },
  'createWantedList.minBudget': { en: 'Minimum Budget (MMK)', mm: 'အနည်းဆုံးဘတ်ဂျက် (မြန်မာကျပ်)' },
  'createWantedList.maxBudget': { en: 'Maximum Budget (MMK)', mm: 'အများဆုံးဘတ်ဂျက် (မြန်မာကျပ်)' },
  'createWantedList.bedrooms': { en: 'Bedrooms', mm: 'အိပ်ခန်းများ' },
  'createWantedList.bathrooms': { en: 'Bathrooms', mm: 'ရေချိုးခန်းများ' },
  'createWantedList.minArea': { en: 'Minimum Area (sqft)', mm: 'အနည်းဆုံးဧရိယာ (စတုရန်းပေ)' },
  'createWantedList.maxArea': { en: 'Maximum Area (sqft)', mm: 'အများဆုံးဧရိယာ (စတုရန်းပေ)' },
  'createWantedList.fullName': { en: 'Full Name', mm: 'အမည်အပြည့်အစုံ' },
  'createWantedList.phoneNumber': { en: 'Phone Number', mm: 'ဖုန်းနံပါတ်' },
  'createWantedList.emailAddress': { en: 'Email Address', mm: 'အီးမေးလ်လိပ်စာ' },
  'createWantedList.specialRequirements': { en: 'Special Requirements', mm: 'အထူးလိုအပ်ချက်များ' },
  'createWantedList.specialRequirementsPlaceholder': { en: 'Any special requirements, preferences, or additional details...', mm: 'မည်သည့်အထူးလိုအပ်ချက်၊ နှစ်သက်မှု၊ သို့မဟုတ်အပိုအသေးစိတ်များ...' },
  'createWantedList.createListing': { en: 'Create Wanted Listing', mm: 'လိုချင်သောစာရင်းဖန်တီးရန်' },
  'createWantedList.creating': { en: 'Creating...', mm: 'ဖန်တီးနေသည်...' },
    'createWantedList.cancel': { en: 'Cancel', mm: 'ပယ်ဖျက်ရန်' },
    'createWantedList.back': { en: 'Back', mm: 'နောက်သို့' },
    'createWantedList.successMessage': { en: 'Your wanted listing has been created successfully!', mm: 'သင့်လိုချင်သောစာရင်းကိုအောင်မြင်စွာဖန်တီးပြီးပါပြီ!' },
    'createWantedList.successTitle': { en: 'Success!', mm: 'အောင်မြင်ပါပြီ!' },
    'createWantedList.errorMessage': { en: 'Failed to create wanted listing. Please try again.', mm: 'လိုချင်သောစာရင်းဖန်တီးရန်မအောင်မြင်ပါ။ ကျေးဇူးပြု၍ထပ်ကြိုးစားပါ။' },
    'createWantedList.errorTitle': { en: 'Error', mm: 'အမှား' },
    'createWantedList.selectType': { en: 'Select type', mm: 'အမျိုးအစားရွေးချယ်ပါ' },
    'createWantedList.selectPropertyType': { en: 'Select property type', mm: 'အိမ်ခြံမြေအမျိုးအစားရွေးချယ်ပါ' },
    'createWantedList.selectRegion': { en: 'Select region', mm: 'ဒေသရွေးချယ်ပါ' },
    'createWantedList.selectTownship': { en: 'Select township', mm: 'မြို့နယ်ရွေးချယ်ပါ' },
    'createWantedList.any': { en: 'Any', mm: 'မည်သည့်အရာ' },
    
    // Validation Error Messages - Field-specific
    'validation.wantedType.required': { en: 'Please select if you are a buyer or renter', mm: 'သင်သည် ဝယ်သူ သို့မဟုတ် ငှားသူ ဖြစ်ကြောင်း ရွေးချယ်ပါ' },
    'validation.wantedType.invalid': { en: 'Please select a valid option', mm: 'မှန်ကန်သော ရွေးချယ်မှုတစ်ခုကို ရွေးချယ်ပါ' },
    
    'validation.propertyType.required': { en: 'Please select a property type', mm: 'အိမ်ခြံမြေအမျိုးအစားကို ရွေးချယ်ပါ' },
    'validation.propertyType.invalid': { en: 'Please select a valid property type', mm: 'မှန်ကန်သော အိမ်ခြံမြေအမျိုးအစားကို ရွေးချယ်ပါ' },
    
    'validation.title.required': { en: 'Title is required', mm: 'ခေါင်းစဉ်လိုအပ်ပါသည်' },
    'validation.title.minLength': { en: 'Title must be at least 10 characters', mm: 'ခေါင်းစဉ်သည် အနည်းဆုံး ၁၀ လုံးရှိရပါမည်' },
    
    'validation.region.required': { en: 'Please select a region', mm: 'တိုင်းဒေသကြီးကို ရွေးချယ်ပါ' },
    
    'validation.township.required': { en: 'Please select a township', mm: 'မြို့နယ်ကို ရွေးချယ်ပါ' },
    
    'validation.name.required': { en: 'Full name is required', mm: 'အမည်အပြည့်အစုံ လိုအပ်ပါသည်' },
    'validation.name.minLength': { en: 'Name must be at least 2 characters', mm: 'အမည်သည် အနည်းဆုံး ၂ လုံးရှိရပါမည်' },
    
    'validation.phone.required': { en: 'Phone number is required', mm: 'ဖုန်းနံပါတ် လိုအပ်ပါသည်' },
    'validation.phone.invalid': { en: 'Phone number must be 9-11 digits', mm: 'ဖုန်းနံပါတ်သည် ၉-၁၁ လုံးရှိရပါမည်' },
    
    'validation.email.invalid': { en: 'Please enter a valid email address', mm: 'မှန်ကန်သော အီးမေးလ်လိပ်စာကို ရိုက်ထည့်ပါ' },
    
    'validation.budget.positive': { en: 'Budget must be a positive number', mm: 'ဘတ်ဂျက်သည် အပေါင်းကိန်းဖြစ်ရပါမည်' },
    'validation.budget.range': { en: 'Maximum budget must be greater than minimum budget', mm: 'အများဆုံးဘတ်ဂျက်သည် အနည်းဆုံးဘတ်ဂျက်ထက် ကြီးရပါမည်' },
    
    'validation.bedrooms.integer': { en: 'Number of bedrooms must be a whole number', mm: 'အိပ်ခန်းအရေအတွက်သည် ကိန်းပြည့်ဖြစ်ရပါမည်' },
    'validation.bedrooms.positive': { en: 'Number of bedrooms must be 0 or greater', mm: 'အိပ်ခန်းအရေအတွက်သည် ၀ သို့မဟုတ် ပိုကြီးရပါမည်' },
    
    'validation.bathrooms.integer': { en: 'Number of bathrooms must be a whole number', mm: 'ရေချိုးခန်းအရေအတွက်သည် ကိန်းပြည့်ဖြစ်ရပါမည်' },
    'validation.bathrooms.positive': { en: 'Number of bathrooms must be 0 or greater', mm: 'ရေချိုးခန်းအရေအတွက်သည် ၀ သို့မဟုတ် ပိုကြီးရပါမည်' },
    
    'validation.area.positive': { en: 'Area must be a positive number', mm: 'ဧရိယာသည် အပေါင်းကိန်းဖြစ်ရပါမည်' },
    'validation.area.range': { en: 'Maximum area must be greater than minimum area', mm: 'အများဆုံးဧရိယာသည် အနည်းဆုံးဧရိယာထက် ကြီးရပါမည်' },
    
    // Legacy validation messages (keeping for backward compatibility)
    'validation.required': { en: 'is required', mm: 'ဖြည့်ရန် လိုအပ်ပါသည်' },
    'validation.budgetRange': { en: 'Minimum budget must be less than or equal to maximum budget', mm: 'အနည်းဆုံးဘတ်ဂျက်သည် အများဆုံးဘတ်ဂျက်ထက် နည်းရမည် သို့မဟုတ် ညီမျှရမည်' },
    'validation.areaRange': { en: 'Minimum area must be less than or equal to maximum area', mm: 'အနည်းဆုံးဧရိယာသည် အများဆုံးဧရိယာထက် နည်းရမည် သို့မဟုတ် ညီမျှရမည်' },
    
    // Form Placeholders
    'placeholders.minBudget': { en: 'e.g., 50000000', mm: 'ဥပမာ၊ ၅၀၀၀၀၀၀၀' },
    'placeholders.maxBudget': { en: 'e.g., 80000000', mm: 'ဥပမာ၊ ၈၀၀၀၀၀၀၀' },
    'placeholders.minArea': { en: 'e.g., 1200', mm: 'ဥပမာ၊ ၁၂၀၀' },
    'placeholders.maxArea': { en: 'e.g., 2000', mm: 'ဥပမာ၊ ၂၀၀၀' },
    'placeholders.fullName': { en: 'Your full name', mm: 'သင့်အမည်အပြည့်အစုံ' },
    'placeholders.phoneNumber': { en: 'e.g., 09123456789', mm: 'ဥပမာ၊ ၀၉၁၂၃၄၅၆၇၈၉' },
    'placeholders.emailAddress': { en: 'your.email@example.com', mm: 'your.email@example.com' },
  'categories.propertyDeveloper': { en: 'Property Developer', mm: 'အိမ်ခြံမြေဖွံ့ဖြိုးတိုးတက်ရေးကုမ္ပဏီ' },
  'categories.realEstateConsultant': { en: 'Real Estate Consultant', mm: 'အိမ်ခြံမြေအကြံပေးကုမ္ပဏီ' },
  
  // Listings
  'listings.forSale': { en: 'For Sale', mm: 'ရောင်းချရန်' },
  'listings.forRent': { en: 'For Rent', mm: 'ငှားရန်ရှိသည်' },
  'listings.title': { en: 'Featured Properties', mm: 'အထူးအိမ်ခြံမြေများ' },
  'listings.subtitle': { en: 'Discover premium properties handpicked for you', mm: 'သင့်အတွက်ရွေးချယ်ထားသောအဆင့်မြင့်အိမ်ခြံမြေများကိုရှာဖွေပါ' },
  'listings.viewAll': { en: 'View All Properties', mm: 'အိမ်ခြံမြေအားလုံးကြည့်ရန်' },
  'listings.viewDetails': { en: 'View Details', mm: 'အသေးစိတ်ကြည့်ရန်' },
  'listings.featured': { en: 'Featured', mm: 'အထူးဖြစ်သော' },
  'listings.sqft': { en: 'sqft', mm: 'စတုရန်းပေ' },
  
  // Create Listing
  'createListing.title': { en: 'Create Listing', mm: 'စာရင်းဖန်တီးရန်' },
  'createListing.propertyPost': { en: 'Property Post', mm: 'အိမ်ခြံမြေတင်ရန်' },
  'createListing.wantedPost': { en: 'Wanted Post', mm: 'လိုချင်သောစာရင်း' },
  'createListing.advertisementPost': { en: 'Advertisement Post', mm: 'ကြော်ငြာတင်ရန်' },
  'createListing.appointmentRequest': { en: 'Appointment Request', mm: 'ချိန်းဆိုမှုတောင်းဆိုရန်' },
  'createListing.giveYourReview': { en: 'Give Your Review', mm: 'သင်၏သုံးသပ်ချက်ပေးပါ' },
  'createListing.jobPostCreate': { en: 'Job Post Create', mm: 'အလုပ်စာရင်းဖန်တီးရန်' },
  
  // Calculators
  'calculators.loanCalculator': { en: 'Loan Calculator', mm: 'ချေးငွေတွက်စက်' },
  'calculators.yarPyatTaxCalculator': { en: 'Yar Pyat Tax Calculator', mm: 'ရာပြတ်ခွန်တွက်စက်' },
  
  // Services
  'services.ourServices': { en: 'Our Services', mm: 'ကျွန်ုပ်တို့၏ဝန်ဆောင်မှုများ' },
  'services.propertyManagement': { en: 'Property Management', mm: 'အိမ်ခြံမြေစီမံခန့်ခွဲမှု' },
  'services.pointManagement': { en: 'Point Management', mm: 'ပွိုင့်စီမံခန့်ခွဲမှု' },
  'services.pointManagementDesc': { en: 'Manage your reward points', mm: 'သင့်ဆုလာဘ်ပွိုင့်များကို စီမံပါ' },
  'services.createListing': { en: 'Create Listing', mm: 'စာရင်းဖန်တီးရန်' },
  'services.createListingDesc': { en: 'Post new property listings', mm: 'အိမ်ခြံမြေစာရင်းအသစ်တင်ရန်' },
  'services.wantedListing': { en: 'Wanted Listing', mm: 'လိုချင်သောစာရင်း' },
  'services.wantedListingDesc': { en: 'Post your property requirements', mm: 'သင့်အိမ်ခြံမြေလိုအပ်ချက်များတင်ရန်' },
  'services.history': { en: 'History', mm: 'မှတ်တမ်း' },
  'services.historyDesc': { en: 'View your activity history', mm: 'သင့်လုပ်ဆောင်ချက်မှတ်တမ်းကြည့်ရန်' },
  'services.appointmentRequest': { en: 'Appointment Request', mm: 'ချိန်းဆိုမှုတောင်းဆိုမှု' },
  'services.appointmentRequestDesc': { en: 'Schedule property viewings', mm: 'အိမ်ခြံမြေကြည့်ရှုမှုချိန်းဆိုရန်' },
  'services.advertisement': { en: 'Advertisement Create & History', mm: 'ကြော်ငြာဖန်တီးမှုနှင့်မှတ်တမ်း' },
  'services.advertisementDesc': { en: 'Create and manage ads', mm: 'ကြော်ငြာများဖန်တီး၍စီမံပါ' },
  'services.companies': { en: 'Companies', mm: 'ကုမ္ပဏီများ' },
  'services.companiesDesc': { en: 'Browse real estate companies', mm: 'အိမ်ခြံမြေကုမ္ပဏီများကြည့်ရန်' },
  'services.knowledgeHub': { en: 'Knowledge Hub', mm: 'အသိပညာဗဟို' },
  'services.knowledgeHubDesc': { en: 'Learn about real estate', mm: 'အိမ်ခြံမြေအကြောင်းလေ့လာပါ' },
  'services.legalTeam': { en: 'Legal Team', mm: 'ဥပဒေအဖွဲ့' },
  'services.legalTeamDesc': { en: 'Legal consultation services', mm: 'ဥပဒေအကြံပြုဝန်ဆောင်မှု' },
  'services.housingEvent': { en: 'Housing Event', mm: 'အိမ်ရာပွဲများ' },
  'services.housingEventDesc': { en: 'Upcoming property events', mm: 'လာမည့်အိမ်ခြံမြေပွဲများ' },
  'services.faq': { en: 'FAQ', mm: 'မကြာခဏမေးလေ့ရှိသောမေးခွန်းများ' },
  'services.faqDesc': { en: 'Frequently asked questions', mm: 'မကြာခဏမေးလေ့ရှိသောမေးခွန်းများ' },
  'services.contactUs': { en: 'Contact Us', mm: 'ဆက်သွယ်ရန်' },
  'services.contactUsDesc': { en: 'Get in touch with us', mm: 'ကျွန်ုပ်တို့နှင့်ဆက်သွယ်ပါ' },
  'services.newsUpdates': { en: 'News & Updates', mm: 'သတင်းနှင့်အပ်ဒိတ်များ' },
  'services.newsUpdatesDesc': { en: 'Latest real estate news', mm: 'နောက်ဆုံးအိမ်ခြံမြေသတင်းများ' },
  'services.applyFeedback': { en: 'Apply Feedback', mm: 'အကြံပြုချက်တင်သွင်းရန်' },
  'services.applyFeedbackDesc': { en: 'Share your suggestions', mm: 'သင့်အကြံပြုချက်များမျှဝေပါ' },
  
  // Feedback Page
  'feedback.seo.title': { en: 'Feedback - Jade Property', mm: 'အကြံပြုချက် - Jade Property' },
  'feedback.seo.description': { en: 'Share your feedback and suggestions to help us improve Jade Property', mm: 'Jade Property ကိုတိုးတက်စေရန်သင့်အကြံပြုချက်များမျှဝေပါ' },
  'feedback.seo.keywords': { en: 'feedback, suggestions, improvement, Jade Property', mm: 'အကြံပြုချက်, အကြံပြုမှု, တိုးတက်မှု, Jade Property' },
  
  'feedback.form.title': { en: 'We Value Your Opinion', mm: 'ကျွန်ုပ်တို့သင့်အမြင်ကိုတန်ဖိုးထားပါသည်' },
  'feedback.form.description': { en: 'Help us improve Jade Property by sharing your thoughts and suggestions', mm: 'သင့်အတွေးများနှင့်အကြံပြုချက်များမျှဝေခြင်းဖြင့် Jade Property ကိုတိုးတက်စေရန်ကူညီပါ' },
  'feedback.form.category': { en: 'Feedback Category', mm: 'အကြံပြုချက်အမျိုးအစား' },
  'feedback.form.selectCategory': { en: 'Select category', mm: 'အမျိုးအစားရွေးချယ်ပါ' },
  'feedback.form.rating': { en: 'Overall Rating', mm: 'စုစုပေါင်းအဆင့်သတ်မှတ်ချက်' },
  'feedback.form.ratingSelected': { en: 'You rated: {rating} star(s)', mm: 'သင်အဆင့်သတ်မှတ်ခဲ့သည်: {rating} ကြယ်(များ)' },
  'feedback.form.name': { en: 'Name', mm: 'အမည်' },
  'feedback.form.namePlaceholder': { en: 'Your name', mm: 'သင့်အမည်' },
  'feedback.form.email': { en: 'Email', mm: 'အီးမေးလ်' },
  'feedback.form.emailPlaceholder': { en: 'your.email@example.com', mm: 'your.email@example.com' },
  'feedback.form.phone': { en: 'Phone (Optional)', mm: 'ဖုန်း (ရွေးချယ်ရန်)' },
  'feedback.form.phonePlaceholder': { en: 'Your phone number', mm: 'သင့်ဖုန်းနံပါတ်' },
  'feedback.form.subject': { en: 'Subject', mm: 'ခေါင်းစဉ်' },
  'feedback.form.subjectPlaceholder': { en: 'Brief summary of your feedback', mm: 'သင့်အကြံပြုချက်၏အတိုချုပ်' },
  'feedback.form.message': { en: 'Your Feedback', mm: 'သင့်အကြံပြုချက်' },
  'feedback.form.messagePlaceholder': { en: 'Please share your thoughts, suggestions, or concerns...', mm: 'သင့်အတွေးများ၊ အကြံပြုချက်များ သို့မဟုတ် စိုးရိမ်မှုများကိုမျှဝေပါ...' },
  'feedback.form.submit': { en: 'Submit Feedback', mm: 'အကြံပြုချက်တင်သွင်းရန်' },
  'feedback.form.submitting': { en: 'Submitting...', mm: 'တင်သွင်းနေသည်...' },
  
  'feedback.categories.general': { en: 'General Feedback', mm: 'ယေဘုယျအကြံပြုချက်' },
  'feedback.categories.feature': { en: 'Feature Request', mm: 'အင်္ဂါရပ်တောင်းဆိုမှု' },
  'feedback.categories.bug': { en: 'Bug Report', mm: 'ချို့ယွင်းချက်အစီရင်ခံချက်' },
  'feedback.categories.improvement': { en: 'Improvement Suggestion', mm: 'တိုးတက်မှုအကြံပြုချက်' },
  'feedback.categories.complaint': { en: 'Complaint', mm: 'တိုင်ကြားမှု' },
  'feedback.categories.compliment': { en: 'Compliment', mm: 'ချီးမွမ်းမှု' },
  
  'feedback.success.title': { en: 'Thank You for Your Feedback!', mm: 'သင့်အကြံပြုချက်အတွက်ကျေးဇူးတင်ပါသည်!' },
  'feedback.success.message': { en: 'Your feedback has been submitted successfully. We appreciate your input and will review it carefully.', mm: 'သင့်အကြံပြုချက်ကိုအောင်မြင်စွာတင်သွင်းပြီးပါပြီ။ သင့်အကြံပြုချက်ကိုကျွန်ုပ်တို့တန်ဖိုးထားပြီး ဂရုတစိုက်ပြန်လည်သုံးသပ်ပါမည်။' },
  'feedback.success.note': { en: 'We will get back to you if needed. Thank you for helping us improve!', mm: 'လိုအပ်ပါက ကျွန်ုပ်တို့သင့်ထံပြန်လည်ဆက်သွယ်ပါမည်။ ကျွန်ုပ်တို့တိုးတက်စေရန်ကူညီပေးသည့်အတွက်ကျေးဇူးတင်ပါသည်!' },
  
  'feedback.info.message': { en: 'Your feedback helps us create a better experience for everyone. Thank you for taking the time to share your thoughts!', mm: 'သင့်အကြံပြုချက်သည် လူတိုင်းအတွက်ပိုမိုကောင်းမွန်သောအတွေ့အကြုံကိုဖန်တီးရန်ကူညီပါသည်။ သင့်အတွေးများမျှဝေရန်အချိန်ပေးသည့်အတွက်ကျေးဇူးတင်ပါသည်!' },

  'feedback.error.title': { en: 'Submission Failed', mm: 'တင်သွင်းမှုမအောင်မြင်ပါ' },
  'feedback.error.message': { en: 'There was an error submitting your feedback. Please try again later.', mm: 'သင့်အကြံပြုချက်တင်သွင်းရာတွင်အမှားတစ်ခုရှိပါသည်။ ကျေးဇူးပြု၍နောက်မှထပ်ကြိုးစားပါ။' },
  'services.favorite': { en: 'Favorite', mm: 'အကြိုက်ဆုံး' },
  'services.favoriteDesc': { en: 'Your saved properties', mm: 'သင်သိမ်းထားသောအိမ်ခြံမြေများ' },
  'services.recentViews': { en: 'Recent Views', mm: 'မကြာသေးမီကြည့်ရှုမှုများ' },
  'services.recentViewsDesc': { en: 'Recently viewed properties', mm: 'မကြာသေးမီကြည့်ရှုခဲ့သောအိမ်ခြံမြေများ' },
  'services.profile': { en: 'Profile', mm: 'ပရိုဖိုင်' },
  'services.profileDesc': { en: 'Manage your account', mm: 'သင့်အကောင့်စီမံပါ' },
  'services.setting': { en: 'Setting', mm: 'ဆက်တင်' },
  'services.settingDesc': { en: 'App preferences and settings', mm: 'အက်ပ်နှစ်သက်မှုနှင့်ဆက်တင်များ' },
  'services.aboutApp': { en: 'About App', mm: 'အက်ပ်အကြောင်း' },
  'services.aboutAppDesc': { en: 'App information and version', mm: 'အက်ပ်အချက်အလက်နှင့်ဗားရှင်း' },
  'services.informationCenter': { en: 'Information Center', mm: 'သတင်းအချက်အလက်ဗဟို' },
  'services.userFeatures': { en: 'User Features', mm: 'အသုံးပြုသူဝန်ဆောင်မှုများ' },
  'services.loanRequest': { en: 'Loan Request', mm: 'ချေးငွေတောင်းဆိုမှု' },
  'services.loanRequestDesc': { en: 'Apply for property loans and financing', mm: 'အိမ်ခြံမြေချေးငွေနှင့်ဘဏ္ဍာရေးတောင်းဆိုရန်' },
  'services.loanCalculator': { en: 'Loan Calculator', mm: 'ချေးငွေတွက်စက်' },
  'services.loanCalculatorDesc': { en: 'Calculate your monthly loan payments', mm: 'သင့်လစဉ်ချေးငွေပေးချေမှုကိုတွက်ချက်ပါ' },
  'services.jobPostListing': { en: 'Job Post Listing', mm: 'အလုပ်ခန့်စာရင်း' },
  'services.jobPostListingDesc': { en: 'Browse available job opportunities', mm: 'ရရှိနိုင်သောအလုပ်အကိုင်အခွင့်အလမ်းများကြည့်ရှုပါ' },
  'services.reviewPost': { en: 'Review Post', mm: 'သုံးသပ်ချက်တင်ရန်' },
  'services.reviewPostDesc': { en: 'Share your property reviews and experiences', mm: 'သင်၏အိမ်ခြံမြေသုံးသပ်ချက်နှင့်အတွေ့အကြုံများမျှဝေပါ' },
  'services.searchAll': { en: 'Search All Property', mm: 'အိမ်ခြံမြေအားလုံးရှာဖွေရန်' },
  'services.searchAllDesc': { en: 'Search properties, advertisements, and events', mm: 'အိမ်ခြံမြေများ၊ ကြော်ငြာများနှင့် အခမ်းအနားများကို ရှာဖွေပါ' },
  'services.aboutUs': { en: 'About Us', mm: 'ကျွန်ုပ်တို့အကြောင်း' },
  'services.homeLoanRequest': { en: 'Loan Request', mm: 'ချေးငွေတောင်းဆိုမှု' },
  
  // Property Types
  'propertyTypes.recommendedTitle': { en: 'Recommended Property Types', mm: 'အကြံပြုထားသောအိမ်ခြံမြေအမျိုးအစားများ' },
  'propertyTypes.apartment': { en: 'Apartment', mm: 'တိုက်ခန်း' },
  'propertyTypes.beachHouse': { en: 'Beach House', mm: 'ပင်လယ်ကမ်းခြေအိမ်' },
  'propertyTypes.commercialBuilding': { en: 'Commercial Building', mm: 'စီးပွားရေးအဆောက်အအုံ' },
  'propertyTypes.condo': { en: 'Condominium', mm: 'ကွန်ဒို' },
  'propertyTypes.duplex': { en: 'Duplex', mm: 'ဒူပလက်စ်' },
  'propertyTypes.factory': { en: 'Factory', mm: 'စက်ရုံ' },
  'propertyTypes.farm': { en: 'Farm', mm: 'လယ်ယာ' },
  'propertyTypes.garden': { en: 'Garden', mm: 'ဥယျာဉ်' },
  'propertyTypes.guestHouse': { en: 'Guest House', mm: 'ဧည့်အိမ်' },
  'propertyTypes.hotel': { en: 'Hotel', mm: 'ဟိုတယ်' },
  'propertyTypes.house': { en: 'House', mm: 'အိမ်' },
  'propertyTypes.land': { en: 'Land', mm: 'မြေ' },
  'propertyTypes.officeSpace': { en: 'Office Space', mm: 'ရုံးခန်း' },
  'propertyTypes.penthouse': { en: 'Penthouse', mm: 'ပင်တဟောက်' },
  'propertyTypes.restaurant': { en: 'Restaurant', mm: 'စားသောက်ဆိုင်' },
  'propertyTypes.shop': { en: 'Shop', mm: 'ဆိုင်' },
  'propertyTypes.studio': { en: 'Studio', mm: 'စတူဒီယို' },
  'propertyTypes.townhouse': { en: 'Townhouse', mm: 'မြို့အိမ်' },
  'propertyTypes.villa': { en: 'Villa', mm: 'ဗီလာ' },
  'propertyTypes.warehouse': { en: 'Warehouse', mm: 'ကုန်သိုလှောင်ရုံ' },
  
  // Search
  'search.keywords': { en: 'Keywords', mm: 'သော့ချက်စာလုံးများ' },
  'search.propertyType': { en: 'Property Type', mm: 'အိမ်ခြံမြေအမျိုးအစား' },
  'search.allTypes': { en: 'All Types', mm: 'အမျိုးအစားအားလုံး' },
  'search.residential': { en: 'Residential', mm: 'နေထိုင်ရေးအိမ်ခြံမြေ' },
  'search.commercial': { en: 'Commercial', mm: 'စီးပွားရေးအိမ်ခြံမြေ' },
  'search.industrial': { en: 'Industrial', mm: 'စက်မှုအိမ်ခြံမြေ' },
  'search.land': { en: 'Land', mm: 'မြေ' },
  'search.regionState': { en: 'Region/State', mm: 'တိုင်း/ပြည်နယ်' },
  'search.all': { en: 'All', mm: 'အားလုံး' },
  'search.yangon': { en: 'Yangon', mm: 'ရန်ကုန်' },
  'search.mandalay': { en: 'Mandalay', mm: 'မန္တလေး' },
  'search.naypyidaw': { en: 'Naypyidaw', mm: 'နေပြည်တော်' },
  'search.bago': { en: 'Bago', mm: 'ပဲခူး' },
  'search.ayeyarwady': { en: 'Ayeyarwady', mm: 'ဧရာဝတီ' },
  'search.shan': { en: 'Shan', mm: 'ရှမ်း' },
  'search.kachin': { en: 'Kachin', mm: 'ကချင်' },
  'search.kayah': { en: 'Kayah', mm: 'ကယား' },
  'search.kayin': { en: 'Kayin', mm: 'ကရင်' },
  'search.chin': { en: 'Chin', mm: 'ချင်း' },
  'search.mon': { en: 'Mon', mm: 'မွန်' },
  'search.rakhine': { en: 'Rakhine', mm: 'ရခိုင်' },
  'search.sagaing': { en: 'Sagaing', mm: 'စစ်ကိုင်း' },
  'search.tanintharyi': { en: 'Tanintharyi', mm: 'တနင်္သာရီ' },
  'search.magway': { en: 'Magway', mm: 'မကွေး' },
  'search.propertyListing': { en: 'Property Listing', mm: 'အိမ်ခြံမြေစာရင်း' },
  'search.forSale': { en: 'For Sale', mm: 'ရောင်းချရန်' },
  'search.forRent': { en: 'For Rent', mm: 'ငှားရန်ရှိသည်' },
  'search.forLease': { en: 'For Lease', mm: 'ငှားရမ်းရန်' },
  'search.propertyCondition': { en: 'Property Condition', mm: 'အိမ်ခြံမြေအခြေအနေ' },
  'search.brandNew': { en: 'Brand New', mm: 'အသစ်စက်စက်' },
  'search.excellent': { en: 'Excellent', mm: 'အလွန်ကောင်းမွန်' },
  'search.good': { en: 'Good', mm: 'ကောင်းမွန်' },
  'search.fair': { en: 'Fair', mm: 'အလယ်အလတ်' },
  'search.needsRenovation': { en: 'Needs Renovation', mm: 'ပြန်လည်ပြင်ဆင်ရန်လိုအပ်' },
  'search.region': { en: 'Region', mm: 'တိုင်း' },
  'search.township': { en: 'Township', mm: 'မြို့နယ်' },
  'search.bahan': { en: 'Bahan', mm: 'ဗဟန်း' },
  'search.kamayut': { en: 'Kamayut', mm: 'ကမာရွတ်' },
  'search.yankin': { en: 'Yankin', mm: 'ရန်ကင်း' },
  'search.sanchaung': { en: 'Sanchaung', mm: 'စမ်းချောင်း' },
  'search.hlaing': { en: 'Hlaing', mm: 'လှိုင်' },
  'search.mayangone': { en: 'Mayangone', mm: 'မရမ်းကုန်း' },
  'search.priceRange': { en: 'Price Range', mm: 'ဈေးနှုန်းအကွာအဝေး' },
  'search.bedrooms': { en: 'Bedrooms', mm: 'အိပ်ခန်းများ' },
  'search.bathrooms': { en: 'Bathrooms', mm: 'ရေချိုးခန်းများ' },
  'search.any': { en: 'Any', mm: 'မည်သည့်အရာ' },
  'search.areaSize': { en: 'Area Size', mm: 'ဧရိယာအရွယ်အစား' },
  'search.min': { en: 'Min', mm: 'အနည်းဆုံး' },
  'search.max': { en: 'Max', mm: 'အများဆုံး' },
  'search.furnished': { en: 'Furnished', mm: 'ပရိဘောဂပါ' },
  'search.unfurnished': { en: 'Unfurnished', mm: 'ပရိဘောဂမပါ' },
  'search.semiFurnished': { en: 'Semi-Furnished', mm: 'ပရိဘောဂတစ်ပိုင်းပါ' },
  'search.parking': { en: 'Parking', mm: 'ကားရပ်နားရန်' },
  'search.yearBuilt': { en: 'Year Built', mm: 'တည်ဆောက်သည့်နှစ်' },
  'search.amenities': { en: 'Amenities', mm: 'အဆောက်အအုံများ' },
  'search.pool': { en: 'Pool', mm: 'ရေကူးကန်' },
  'search.gym': { en: 'Gym', mm: 'အားကစားခန်း' },
  'search.security': { en: 'Security', mm: 'လုံခြုံရေး' },
  'search.elevator': { en: 'Elevator', mm: 'ဓာတ်လှေကား' },
  'search.garden': { en: 'Garden', mm: 'ဥယျာဉ်' },
  'search.balcony': { en: 'Balcony', mm: 'ပြတင်းပေါက်' },
  'search.wifi': { en: 'WiFi', mm: 'ဝိုင်ဖိုင်' },
  'search.ac': { en: 'Air Conditioning', mm: 'လေအေးပေးစက်' },
  'search.clearFilters': { en: 'Clear Filters', mm: 'စစ်ထုတ်မှုများရှင်းလင်းရန်' },
  'search.searchProperties': { en: 'Search Properties', mm: 'အိမ်ခြံမြေများရှာဖွေရန်' },
  
  // Advertisements
  'ads.title': { en: 'Featured Advertisements', mm: 'အထူးကြော်ငြာများ' },
  'ads.subtitle': { en: 'Discover exclusive offers and promotions', mm: 'သီးသန့်ကမ်းလှမ်းမှုများနှင့်ကြော်ငြာများကိုရှာဖွေပါ' },
  'ads.viewAll': { en: 'View All', mm: 'အားလုံးကြည့်ရန်' },
  'ads.promoted': { en: 'Promoted', mm: 'ကြော်ငြာပေးထား' },
  'ads.validUntil': { en: 'Valid Until', mm: 'သက်တမ်းကုန်ဆုံးရက်' },
  'ads.learnMore': { en: 'Learn More', mm: 'ပိုမိုလေ့လာရန်' },
  
  // Premium
  'premium.title': { en: 'Premium Properties', mm: 'အဆင့်မြင့်အိမ်ခြံမြေများ' },
  'premium.subtitle': { en: 'Exclusive luxury properties for discerning buyers', mm: 'ရွေးချယ်တတ်သောဝယ်သူများအတွက်သီးသန့်ဇိမ်ခံအိမ်ခြံမြေများ' },
  'premium.viewAll': { en: 'View All Premium', mm: 'အဆင့်မြင့်အားလုံးကြည့်ရန်' },
  'premium.badge': { en: 'Premium', mm: 'အဆင့်မြင့်' },
  'premium.trending': { en: 'Trending', mm: 'ခေတ်စားနေ' },
  
  // Events
  'events.title': { en: 'Upcoming Events', mm: 'လာမည့်အခမ်းအနားများ' },
  'events.subtitle': { en: 'Join our real estate events and workshops', mm: 'ကျွန်ုပ်တို့၏အိမ်ခြံမြေအခမ်းအနားများနှင့်လုပ်ငန်းဆိုင်ရာသင်တန်းများတွင်ပါဝင်ပါ' },
  'events.viewAll': { en: 'View All Events', mm: 'အခမ်းအနားအားလုံးကြည့်ရန်' },
  'events.liveNow': { en: 'Live Now', mm: 'ယခုတိုက်ရိုက်ထုတ်လွှင့်နေ' },
  'events.upcoming': { en: 'Upcoming', mm: 'လာမည့်' },
  'events.ended': { en: 'Ended', mm: 'ပြီးဆုံးပြီ' },
  'events.attending': { en: 'attending', mm: 'တက်ရောက်မည်' },
  'events.eventEnded': { en: 'Event Ended', mm: 'အခမ်းအနားပြီးဆုံးပြီ' },
  'events.registerNow': { en: 'Register Now', mm: 'ယခုစာရင်းသွင်းပါ' },
  
  // Jobs
  'jobs.title': { en: 'Job Opportunities', mm: 'အလုပ်အကိုင်အခွင့်အလမ်းများ' },
  'jobs.subtitle': { en: 'Find your next career in real estate', mm: 'အိမ်ခြံမြေတွင်သင်၏နောက်အလုပ်အကိုင်ကိုရှာဖွေပါ' },
  'jobs.viewAll': { en: 'View All Jobs', mm: 'အလုပ်အားလုံးကြည့်ရန်' },
  'jobs.fullTime': { en: 'Full Time', mm: 'အချိန်ပြည့်' },
  'jobs.postedOn': { en: 'Posted on', mm: 'တင်ထားသည့်ရက်' },
  'jobs.viewDetails': { en: 'View Details', mm: 'အသေးစိတ်ကြည့်ရန်' },
  
  // Legal Team
  'legalTeam.title': { en: 'Our Legal Team', mm: 'ကျွန်ုပ်တို့၏ဥပဒေအဖွဲ့' },
  'legalTeam.subtitle': { en: 'Expert legal advice for your property needs', mm: 'သင်၏အိမ်ခြံမြေလိုအပ်ချက်များအတွက်ကျွမ်းကျင်သောဥပဒေအကြံပြုချက်' },
  'legalTeam.viewAll': { en: 'View All Team', mm: 'အဖွဲ့အားလုံးကြည့်ရန်' },
  
  // Language
  'language.english': { en: 'English', mm: 'အင်္ဂလိပ်' },
  'language.myanmar': { en: 'Myanmar', mm: 'မြန်မာ' },
  
  // Footer
  'footer.description': { en: 'Your trusted partner in finding the perfect property.', mm: 'သင့်အတွက် အကောင်းဆုံး အိမ်ခြံမြေကို ရှာဖွေရာတွင် ယုံကြည်စိတ်ချရသော လုပ်ဖော်ကိုင်ဖက်' },
  'footer.quickLinks': { en: 'Quick Links', mm: 'အမြန်လင့်ခ်များ' },
  'footer.legal': { en: 'Legal', mm: 'ဥပဒေဆိုင်ရာ' },
  'footer.contact': { en: 'Contact Us', mm: 'ဆက်သွယ်ရန်' },
  'footer.privacy': { en: 'Privacy Policy', mm: 'ကိုယ်ရေးကိုယ်တာမူဝါဒ' },
  'footer.terms': { en: 'Terms of Service', mm: 'ဝန်ဆောင်မှုစည်းမျဉ်းများ' },
  'footer.rights': { en: 'All rights reserved.', mm: 'မူပိုင်ခွင့်များ လုံးဝ ရယူထားပါသည်။' },
  
  // Privacy Policy
  'privacyPolicy.title': { en: 'Privacy Policy', mm: 'ကိုယ်ရေးကိုယ်တာမူဝါဒ' },
  'privacyPolicy.subtitle': { en: 'How we collect, use, and protect your personal information', mm: 'ကျွန်ုပ်တို့သည် သင့်ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို မည်သို့စုဆောင်း၊ အသုံးပြုနှင့် ကာကွယ်ပေးသည်ကို လေ့လာပါ' },
  'privacyPolicy.lastUpdated': { en: 'Last Updated', mm: 'နောက်ဆုံးအပ်ဒိတ်' },
  'privacyPolicy.backToTop': { en: 'Back to Top', mm: 'အပေါ်သို့ပြန်သွားရန်' },
  
  // SEO
  'privacyPolicy.seo.title': { en: 'Privacy Policy - Jade Property', mm: 'ကိုယ်ရေးကိုယ်တာမူဝါဒ - Jade Property' },
  'privacyPolicy.seo.description': { en: 'Learn how Jade Property collects, uses, and protects your personal information. Our comprehensive privacy policy covers data collection, security, and your rights.', mm: 'Jade Property သည် သင့်ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို မည်သို့စုဆောင်း၊ အသုံးပြုနှင့် ကာကွယ်ပေးသည်ကို လေ့လာပါ။' },
  'privacyPolicy.seo.keywords': { en: 'privacy policy, data protection, personal information, Jade Property, Myanmar real estate', mm: 'ကိုယ်ရေးကိုယ်တာမူဝါဒ, အချက်အလက်ကာကွယ်ရေး, ကိုယ်ရေးကိုယ်တာအချက်အလက်' },
  
  // Table of Contents
  'privacyPolicy.toc.title': { en: 'Table of Contents', mm: 'မာတိကာ' },
  'privacyPolicy.toc.introduction': { en: 'Introduction', mm: 'မိတ်ဆက်' },
  'privacyPolicy.toc.definition': { en: 'Definition of Personal Data', mm: 'ကိုယ်ရေးကိုယ်တာအချက်အလက်၏ အဓိပ္ပါယ်' },
  'privacyPolicy.toc.whyCollect': { en: 'Why We Collect Personal Data', mm: 'ကျွန်ုပ်တို့ဘာ့ကြောင့် ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို စုဆောင်းရသနည်း' },
  'privacyPolicy.toc.howCollect': { en: 'How We Collect Personal Data', mm: 'ကျွန်ုပ်တို့သည် ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို မည်သို့စုဆောင်းသနည်း' },
  'privacyPolicy.toc.dataDisclosure': { en: 'Data Disclosure', mm: 'အချက်အလက်မျှဝေခြင်း' },
  'privacyPolicy.toc.retention': { en: 'Retention of Personal Data', mm: 'ကိုယ်ရေးကိုယ်တာအချက်အလက်များ သိမ်းဆည်းခြင်း' },
  'privacyPolicy.toc.security': { en: 'Security of Personal Data', mm: 'ကိုယ်ရေးကိုယ်တာအချက်အလက်များ၏ လုံခြုံရေး' },
  'privacyPolicy.toc.privacyRights': { en: 'Privacy Rights', mm: 'ကိုယ်ရေးကိုယ်တာခွင့်ပြုချက်များ' },
  'privacyPolicy.toc.notifications': { en: 'Push Notifications', mm: 'ပွတ်ရှ်အသိပေးချက်များ' },
  'privacyPolicy.toc.amendments': { en: 'Amendments and Updates', mm: 'ပြင်ဆင်မှုများနှင့် အပ်ဒိတ်များ' },
  'privacyPolicy.toc.contact': { en: 'Contact Us', mm: 'ဆက်သွယ်ရန်' },
  'privacyPolicy.toc.governingLaw': { en: 'Governing Law', mm: 'အုပ်ချုပ်သောဥပဒေ' },
  
  // Sections
  'privacyPolicy.sections.introduction.title': { en: 'INTRODUCTION', mm: 'မိတ်ဆက်' },
  'privacyPolicy.sections.introduction.content': { en: 'This privacy policy (the "Privacy Policy") describes how Jade Property ("we", "us" or "our") collect, store, use, share and protect the personal data of our employees ("you", "users", or "your") through the platform website at Jade Property and mobile application (the "Platforms") that links to this Privacy Policy. This Privacy Policy applies to the users of the Platforms. By accessing the Platforms, submitting information to us (whether through Platforms or otherwise), you agree for us to process your Personal Data, as defined in Clause 2 of this Privacy Policy, and disclosing it to our subsidiaries, affiliates, and our third party service providers in the manner set forth in this Privacy Policy.', mm: 'ဤကိုယ်ရေးကိုယ်တာမူဝါဒ ("ကိုယ်ရေးကိုယ်တာမူဝါဒ") သည် Jade Property ("ကျွန်ုပ်တို့", "ကျွန်ုပ်တို့" သို့မဟုတ် "ကျွန်ုပ်တို့၏") သည် ကျွန်ုပ်တို့၏ဝန်ထမ်းများ ("သင်တို့", "အသုံးပြုသူများ", သို့မဟုတ် "သင့်") ၏ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို Jade Property ပလက်ဖောင်းဝဘ်ဆိုက်နှင့် မိုဘိုင်းအက်ပ်လီကေးရှင်း (ဤကိုယ်ရေးကိုယ်တာမူဝါဒနှင့်ချိတ်ဆက်ထားသော "ပလက်ဖောင်းများ") မှတဆင့် မည်သို့စုဆောင်း၊ သိမ်းဆည်း၊ အသုံးပြုနှင့် ကာကွယ်ပေးသည်ကို ဖော်ပြပါသည်။' },
  'privacyPolicy.sections.introduction.highlight': { en: 'Reading this Privacy Policy will help you understand your privacy rights, our policies, and practices.', mm: 'ဤကိုယ်ရေးကိုယ်တာမူဝါဒကို ဖတ်ရှုခြင်းသည် သင့်ကိုယ်ရေးကိုယ်တာခွင့်ပြုချက်များ၊ ကျွန်ုပ်တို့၏မူဝါဒများနှင့် လုပ်ဆောင်ချက်များကို နားလည်ရန် ကူညီပေးပါမည်။' },
  
  'privacyPolicy.sections.definition.title': { en: 'DEFINITION OF PERSONAL DATA', mm: 'ကိုယ်ရေးကိုယ်တာအချက်အလက်၏ အဓိပ္ပါယ်' },
  'privacyPolicy.sections.definition.content': { en: '"Personal Data" means information about you, from which you are identifiable, including but not limited to your name, employee number, telephone number, date of birth, gender, email address, biometrics, profile photo, and any information about you which you have provided to us.', mm: '"ကိုယ်ရေးကိုယ်တာအချက်အလက်" ဆိုသည်မှာ သင့်အကြောင်းအချက်အလက်များဖြစ်ပြီး၊ သင်ကိုဖော်ထုတ်နိုင်သော အချက်အလက်များဖြစ်သည်။ ယင်းတွင် သင့်အမည်၊ ဝန်ထမ်းနံပါတ်၊ ဖုန်းနံပါတ်၊ မွေးနေ့၊ လိင်၊ အီးမေးလ်လိပ်စာ၊ ဇီဝမှတ်တမ်းများ၊ ပရိုဖိုင်ဓာတ်ပုံ၊ နှင့် သင်ကျွန်ုပ်တို့ထံ ပေးအပ်ထားသော သင့်အကြောင်းအချက်အလက်များ ပါဝင်ပါသည်။' },
  
  'privacyPolicy.sections.whyCollect.title': { en: 'WHY WE COLLECT PERSONAL DATA', mm: 'ကျွန်ုပ်တို့ဘာ့ကြောင့် ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို စုဆောင်းရသနည်း' },
  'privacyPolicy.sections.whyCollect.ageVerification.title': { en: 'Age Verification', mm: 'အသက်အတည်ပြုခြင်း' },
  'privacyPolicy.sections.whyCollect.ageVerification.content': { en: 'Obtaining a date of birth enables us to verify users\' ages, ensuring compliance with legal requirements and age restrictions. This not only helps us provide age-appropriate content but also ensures a safer online environment for users of all ages.', mm: 'မွေးနေ့ရရှိခြင်းသည် ကျွန်ုပ်တို့အား အသုံးပြုသူများ၏အသက်များကို အတည်ပြုနိုင်စေပြီး၊ ဥပဒေအရ လိုအပ်ချက်များနှင့် အသက်ကန့်သတ်ချက်များကို လိုက်နာစေပါသည်။' },
  'privacyPolicy.sections.whyCollect.accountSecurity.title': { en: 'Account Security', mm: 'အကောင့်လုံခြုံရေး' },
  'privacyPolicy.sections.whyCollect.accountSecurity.content': { en: 'Gathering phone numbers enhances account security by enabling two-factor authentication (2FA) and aiding in account recovery processes. Additionally, it facilitates communication by allowing us to send important updates, security alerts, and personalized offers directly to users via SMS.', mm: 'ဖုန်းနံပါတ်များစုဆောင်းခြင်းသည် နှစ်ဆအမျိုးအစားအတည်ပြုခြင်း (2FA) ကို ဖွင့်ပေးခြင်းနှင့် အကောင့်ပြန်လည်ရယူမှုလုပ်ငန်းစဉ်များတွင် ကူညီပေးခြင်းဖြင့် အကောင့်လုံခြုံရေးကို မြှင့်တင်ပေးပါသည်။' },
  'privacyPolicy.sections.whyCollect.cameraAccess.title': { en: 'Camera Access', mm: 'ကင်မရာအသုံးပြုခွင့်' },
  'privacyPolicy.sections.whyCollect.cameraAccess.content': { en: 'The Platforms may seek permission to access your device\'s camera, which is integral to the core functionality and user experience of Platforms. The camera is used for your profile photo updates and document capture.', mm: 'ပလက်ဖောင်းများသည် သင့်စက်ပစ္စည်း၏ကင်မရာအသုံးပြုခွင့်ကို တောင်းဆိုနိုင်ပြီး၊ ယင်းသည် ပလက်ဖောင်းများ၏ အဓိကလုပ်ဆောင်ချက်နှင့် အသုံးပြုသူအတွေ့အကြုံအတွက် အရေးကြီးပါသည်။' },
  'privacyPolicy.sections.whyCollect.cameraAccess.additional': { en: 'Users have the option to update their profile photos directly on the Platforms, enhancing personalization and engagement. Camera access allows for a seamless process, enabling users to capture and upload their photos instantly.', mm: 'အသုံးပြုသူများသည် ပလက်ဖောင်းများပေါ်တွင် သူတို့၏ပရိုဖိုင်ဓာတ်ပုံများကို တိုက်ရိုက်အပ်ဒိတ်လုပ်နိုင်သော ရွေးချယ်စရာရှိပြီး၊ ယင်းသည် ပုဂ္ဂိုလ်ရေးဆိုင်ရာပြုလုပ်ခြင်းနှင့် ပါဝင်မှုကို မြှင့်တင်ပေးပါသည်။' },
  
  'privacyPolicy.sections.howCollect.title': { en: 'HOW WE COLLECT PERSONAL DATA', mm: 'ကျွန်ုပ်တို့သည် ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို မည်သို့စုဆောင်းသနည်း' },
  'privacyPolicy.sections.howCollect.content': { en: 'We collect Personal Data voluntarily provided to us when you are employed for the Jade Property or when you participate in activities on the Platforms, or otherwise when you contact us.', mm: 'ကျွန်ုပ်တို့သည် သင်သည် Jade Property အတွက် အလုပ်လုပ်သောအခါ သို့မဟုတ် သင်သည် ပလက်ဖောင်းများပေါ်တွင် လုပ်ဆောင်ချက်များတွင် ပါဝင်သောအခါ သို့မဟုတ် အခြားနည်းဖြင့် သင်ကျွန်ုပ်တို့နှင့် ဆက်သွယ်သောအခါ ကျွန်ုပ်တို့ထံ စေတနာအလျောက်ပေးအပ်ထားသော ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို စုဆောင်းပါသည်။' },
  'privacyPolicy.sections.howCollect.additional': { en: 'Personal Data that we collect depends on the context of your interactions with us and the Platforms, the choices you make, and the features you use.', mm: 'ကျွန်ုပ်တို့စုဆောင်းသော ကိုယ်ရေးကိုယ်တာအချက်အလက်များသည် သင်ကျွန်ုပ်တို့နှင့် ပလက်ဖောင်းများနှင့် သင်၏အပြန်အလှန်ဆက်သွယ်မှု၊ သင်ရွေးချယ်သောအရာများ၊ နှင့် သင်အသုံးပြုသောလုပ်ဆောင်ချက်များပေါ်တွင် မူတည်ပါသည်။' },
  
  'privacyPolicy.sections.dataDisclosure.title': { en: 'DATA DISCLOSURE', mm: 'အချက်အလက်မျှဝေခြင်း' },
  'privacyPolicy.sections.dataDisclosure.content': { en: 'We reserve the right to share your Personal Data with relevant authorities as may be required by them under applicable law.', mm: 'ကျွန်ုပ်တို့သည် သက်ဆိုင်ရာဥပဒေအရ သင့်ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို သက်ဆိုင်ရာအာဏာပိုင်များနှင့် မျှဝေပိုင်ခွင့်ရှိပါသည်။' },
  
  'privacyPolicy.sections.retention.title': { en: 'RETENTION OF PERSONAL DATA', mm: 'ကိုယ်ရေးကိုယ်တာအချက်အလက်များ သိမ်းဆည်းခြင်း' },
  'privacyPolicy.sections.retention.content': { en: 'We will only keep your Personal Data for as long as it is necessary for the purposes set out in this Privacy Policy, unless a longer retention period is required or permitted by a relevant law (such as for tax, accounting, or other legal requirements).', mm: 'ကျွန်ုပ်တို့သည် သင့်ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို ဤကိုယ်ရေးကိုယ်တာမူဝါဒတွင် သတ်မှတ်ထားသော ရည်ရွယ်ချက်များအတွက် လိုအပ်သလောက်သာ သိမ်းဆည်းထားပါမည်။' },
  'privacyPolicy.sections.retention.additional': { en: 'When we have no ongoing legitimate business requiring us to process your Personal Data, we will either delete or anonymise such information, or, if this is not possible, securely store your Personal Data and segregate it from any further processing until deletion is made possible.', mm: 'ကျွန်ုပ်တို့အား သင့်ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို လုပ်ဆောင်ရန် ဆက်လက်လုပ်ငန်းလိုအပ်ချက်မရှိသောအခါ၊ ကျွန်ုပ်တို့သည် ထိုအချက်အလက်များကို ဖျက်ပစ်မည် သို့မဟုတ် အမည်မဖော်ပြနိုင်အောင် ပြုလုပ်မည်။' },
  
  'privacyPolicy.sections.security.title': { en: 'SECURITY OF PERSONAL DATA', mm: 'ကိုယ်ရေးကိုယ်တာအချက်အလက်များ၏ လုံခြုံရေး' },
  'privacyPolicy.sections.security.measures.title': { en: 'Security Measures', mm: 'လုံခြုံရေးအစီအမံများ' },
  'privacyPolicy.sections.security.measures.content': { en: 'We have implemented appropriate and reasonable technical and organisational security measures designed to protect the security of any Personal Data we process.', mm: 'ကျွန်ုပ်တို့သည် ကျွန်ုပ်တို့လုပ်ဆောင်သော မည်သည့်ကိုယ်ရေးကိုယ်တာအချက်အလက်များ၏ လုံခြုံရေးကို ကာကွယ်ရန်ရည်ရွယ်ထားသော သင့်လျော်ပြီး သင့်တင့်သော နည်းပညာနှင့် အဖွဲ့အစည်းဆိုင်ရာ လုံခြုံရေးအစီအမံများကို အကောင်အထည်ဖော်ထားပါသည်။' },
  'privacyPolicy.sections.security.limitations.title': { en: 'Limitations on Security', mm: 'လုံခြုံရေးအပေါ် ကန့်သတ်ချက်များ' },
  'privacyPolicy.sections.security.limitations.content': { en: 'While we take commercially reasonable steps to help secure and safeguard Personal Data, no security system is impenetrable. Due to the inherent nature of the Internet or information storage technology as an open global communication vehicle, we cannot promise or guarantee that your Personal Data, during transmission to and from our Platforms through any online means, will be absolutely safe from intrusion by others.', mm: 'ကျွန်ုပ်တို့သည် ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို လုံခြုံစေရန်နှင့် ကာကွယ်ရန် ကူညီပေးရန် စီးပွားရေးအရ သင့်တင့်သောအဆင့်များကို ပြုလုပ်သော်လည်း၊ မည်သည့်လုံခြုံရေးစနစ်မျှ ထိုးဖောက်၍မရပါ။' },
  
  'privacyPolicy.sections.privacyRights.title': { en: 'PRIVACY RIGHTS', mm: 'ကိုယ်ရေးကိုယ်တာခွင့်ပြုချက်များ' },
  'privacyPolicy.sections.privacyRights.content': { en: 'We process your Personal Data with your consent, and we respect your privacy rights in accordance with applicable laws. You can withdraw your consent for us to process your Personal Data at any time by serving us a Personal Data withdrawal notice to the contact details provided in Clause 11 of this Privacy Policy.', mm: 'ကျွန်ုပ်တို့သည် သင့်ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို သင့်ခွင့်ပြုချက်ဖြင့် လုပ်ဆောင်ပြီး၊ ကျွန်ုပ်တို့သည် သက်ဆိုင်ရာဥပဒေများနှင့်အညီ သင့်ကိုယ်ရေးကိုယ်တာခွင့်ပြုချက်များကို လေးစားပါသည်။' },
  'privacyPolicy.sections.privacyRights.highlight': { en: 'Please note that serving us a Personal Data withdrawal notice will not affect the lawfulness of the processing of your Personal Data before the Personal Data withdrawal notice has been served to us neither will it affect the processing of your Personal Data conducted in reliance on lawful processing grounds other than consent.', mm: 'ကျွန်ုပ်တို့ထံ ကိုယ်ရေးကိုယ်တာအချက်အလက်ရုပ်သိမ်းခြင်းအသိပေးချက်ပေးခြင်းသည် ကိုယ်ရေးကိုယ်တာအချက်အလက်ရုပ်သိမ်းခြင်းအသိပေးချက်ကို ကျွန်ုပ်တို့ထံ ပေးအပ်မီ သင့်ကိုယ်ရေးကိုယ်တာအချက်အလက်များ၏ လုပ်ဆောင်မှု၏ တရားဝင်မှုကို ထိခိုက်မည်မဟုတ်ပါ။' },
  
  'privacyPolicy.sections.notifications.title': { en: 'THE PLATFORMS\' PUSH NOTIFICATIONS', mm: 'ပလက်ဖောင်းများ၏ ပွတ်ရှ်အသိပေးချက်များ' },
  'privacyPolicy.sections.notifications.content': { en: 'If you use our Platforms, we may request you to send you push notifications regarding your account or certain features of the Platforms. If you wish to opt out from receiving these types of communications, you may turn them off in your device\'s settings.', mm: 'သင်သည် ကျွန်ုပ်တို့၏ပလက်ဖောင်းများကို အသုံးပြုပါက၊ ကျွန်ုပ်တို့သည် သင့်အကောင့် သို့မဟုတ် ပလက်ဖောင်းများ၏ အချို့လုပ်ဆောင်ချက်များနှင့်ပတ်သက်၍ ပွတ်ရှ်အသိပေးချက်များကို ပို့ပေးရန် တောင်းဆိုနိုင်ပါသည်။' },
  
  'privacyPolicy.sections.amendments.title': { en: 'AMENDMENTS AND UPDATES', mm: 'ပြင်ဆင်မှုများနှင့် အပ်ဒိတ်များ' },
  'privacyPolicy.sections.amendments.content': { en: 'We reserve the right to amend and update this Privacy Policy without prior notice to you. The updated version will be indicated by an updated "Revised" date and the updated version will be effective as soon as it is accessible. If we make material changes to this Privacy Policy, we may, but are not obligated to, notify you either by prominently posting a notice of such changes or by directly sending you a notification.', mm: 'ကျွန်ုပ်တို့သည် သင့်အား ကြိုတင်အသိပေးခြင်းမရှိဘဲ ဤကိုယ်ရေးကိုယ်တာမူဝါဒကို ပြင်ဆင်နှင့် အပ်ဒိတ်လုပ်ပိုင်ခွင့်ရှိပါသည်။' },
  
  'privacyPolicy.sections.contact.title': { en: 'CONTACT US', mm: 'ဆက်သွယ်ရန်' },
  'privacyPolicy.sections.contact.subtitle': { en: 'Get in Touch', mm: 'ဆက်သွယ်ရန်' },
  'privacyPolicy.sections.contact.content': { en: 'If you have any questions or concerns about this Privacy Policy, please contact us at:', mm: 'ဤကိုယ်ရေးကိုယ်တာမူဝါဒနှင့်ပတ်သက်၍ မေးခွန်းများ သို့မဟုတ် စိုးရိမ်မှုများရှိပါက၊ ကျေးဇူးပြု၍ ကျွန်ုပ်တို့နှင့် ဆက်သွယ်ပါ:' },
  'privacyPolicy.sections.contact.email': { en: 'Email', mm: 'အီးမေးလ်' },
  
  'privacyPolicy.sections.governingLaw.title': { en: 'GOVERNING LAW', mm: 'အုပ်ချုပ်သောဥပဒေ' },
  'privacyPolicy.sections.governingLaw.content': { en: 'This Privacy Policy is governed in all respects by the laws of Myanmar.', mm: 'ဤကိုယ်ရေးကိုယ်တာမူဝါဒသည် မြန်မာနိုင်ငံ၏ ဥပဒေများဖြင့် အုပ်ချုပ်ပါသည်။' },
  
  // About Us
  'about.story': { en: 'Our Story', mm: 'ကျွန်ုပ်တို့၏ ဇာတ်လမ်း' },
  'about.title': { en: 'About Jade Property', mm: 'Jade Property အကြောင်း' },
  'about.intro': { en: 'We are dedicated to transforming the real estate experience by providing comprehensive, transparent, and technology-driven property solutions that empower our clients to make informed decisions and find their perfect property.', mm: 'ကျွန်ုပ်တို့သည် ဖောက်သည်များအား အကောင်းဆုံးဆုံးဖြတ်ချက်များချနိုင်ရန်နှင့် ၎င်းတို့၏ အကောင်းဆုံးအိမ်ခြံမြေကို ရှာတွေ့နိုင်ရန် ပြည့်စုံသော၊ ပွင့်လင်းမြင်သာသော နှင့် နည်းပညာမောင်းနှင်သော အိမ်ခြံမြေဖြေရှင်းချက်များဖြင့် အိမ်ခြံမြေအတွေ့အကြုံကို ပြောင်းလဲပေးရန် ရည်ရွယ်ပါသည်။' },
  'about.whatWeDo': { en: 'What We Do', mm: 'ကျွန်ုပ်တို့ လုပ်ဆောင်ချက်များ' },
  'about.description1': { en: 'Jade Property is a comprehensive real estate platform that connects buyers, sellers, and investors with their ideal properties. Our platform combines cutting-edge technology with personalized service to deliver an exceptional property search and transaction experience.', mm: 'Jade Property သည် ဝယ်သူများ၊ ရောင်းသူများနှင့် ရင်းနှီးမြှုပ်နှံသူများကို ၎င်းတို့၏ အကောင်းဆုံး အိမ်ခြံမြေများနှင့် ချိတ်ဆက်ပေးသော ပြည့်စုံသော အိမ်ခြံမြေပလက်ဖောင်းတစ်ခုဖြစ်ပါသည်။ ကျွန်ုပ်တို့၏ ပလက်ဖောင်းသည် ထူးခြားသော အိမ်ခြံမြေရှာဖွေမှုနှင့် အရောင်းအဝယ် အတွေ့အကြုံကို ပေးအပ်ရန် အဆင့်မြင့် နည်းပညာနှင့် ပုဂ္ဂိုလ်ရေးဆိုင်ရာ ဝန်ဆောင်မှုကို ပေါင်းစပ်ထားပါသည်။' },
  'about.description2': { en: 'We work with experienced real estate professionals and leverage advanced market analytics to provide our clients with accurate property valuations and investment insights. Whether you\'re a first-time homebuyer or a seasoned investor, our team is dedicated to helping you achieve your real estate goals.', mm: 'ကျွန်ုပ်တို့သည် အတွေ့အကြုံရှိ အိမ်ခြံမြေ ပညာရှင်များနှင့် အလုပ်လုပ်ပြီး ဖောက်သည်များအား တိကျသော အိမ်ခြံမြေတန်ဖိုးသတ်မှတ်ချက်များနှင့် ရင်းနှီးမြှုပ်နှံမှု အသိအမြင်များ ပေးအပ်ရန် အဆင့်မြင့် စျေးကွက်ခွဲခြမ်းစိတ်ဖြာမှုများကို အသုံးပြုပါသည်။ သင်သည် ပထမဆုံးအကြိမ် အိမ်ဝယ်သူဖြစ်စေ၊ အတွေ့အကြုံရှိ ရင်းနှီးမြှုပ်နှံသူဖြစ်စေ၊ ကျွန်ုပ်တို့အဖွဲ့သည် သင်၏ အိမ်ခြံမြေပန်းတိုင်များကို အောင်မြင်အောင် ကူညီပေးရန် ရည်စူးပါသည်။' },
  'about.ourValues': { en: 'Our Values', mm: 'ကျွန်ုပ်တို့၏ တန်ဖိုးများ' },
  'about.mission': { en: 'Our Mission', mm: 'ကျွန်ုပ်တို့၏ မျှော်မှန်းချက်' },
  'about.missionDesc': { en: 'To revolutionize real estate by making property search transparent, efficient, and accessible to everyone through innovative technology.', mm: 'ဆန်းသစ်သော နည်းပညာမှတဆင့် အိမ်ခြံမြေရှာဖွေမှုကို ပွင့်လင်းမြင်သာစေခြင်း၊ ထိရောက်စေခြင်းနှင့် လူတိုင်းအတွက် လက်လှမ်းမီစေခြင်းဖြင့် အိမ်ခြံမြေကို တော်လှန်ပြောင်းလဲရန်။' },
  'about.clientCentric': { en: 'Client-Centric', mm: 'ဖောက်သည်ဗဟိုပြု' },
  'about.clientDesc': { en: 'We prioritize our clients\' needs and work tirelessly to exceed expectations in every transaction.', mm: 'ကျွန်ုပ်တို့သည် ဖောက်သည်များ၏ လိုအပ်ချက်များကို ဦးစားပေးပြီး အရောင်းအဝယ် တိုင်းတွင် မျှော်မှန်းချက်များကို ကျော်လွန်အောင် ကြိုးစားဆောင်ရွက်ပါသည်။' },
  'about.integrity': { en: 'Integrity & Trust', mm: 'သမာဓိနှင့် ယုံကြည်မှု' },
  'about.integrityDesc': { en: 'We are committed to maintaining the highest standards of honesty, transparency, and professionalism in all our dealings.', mm: 'ကျွန်ုပ်တို့၏ ရောင်းဝယ်ဖောက်ကားမှုအားလုံးတွင် ရိုးသားမှု၊ ပွင့်လင်းမြင်သာမှုနှင့် ပညာရှင်ဆန်မှု၏ အမြင့်ဆုံးစံနှုန်းများကို ထိန်းသိမ်းရန် ကတိပြုပါသည်။' },
  'about.meetTeam': { en: 'Meet Our Team', mm: 'ကျွန်ုပ်တို့၏ အဖွဲ့ကို တွေ့ဆုံပါ' },
  'about.contactInfo': { en: 'Contact Information', mm: 'ဆက်သွယ်ရန် အချက်အလက်' },
  'about.email': { en: 'Email', mm: 'အီးမေးလ်' },
  'about.phone': { en: 'Phone', mm: 'ဖုန်း' },
  'about.address': { en: 'Address', mm: 'လိပ်စာ' },
  'about.experience': { en: 'Years of Experience', mm: 'နှစ်များ အတွေ့အကြုံ' },
  'about.experienceDesc': { en: 'Over a decade of expertise in Myanmar\'s real estate market', mm: 'မြန်မာနိုင်ငံ၏ အိမ်ခြံမြေစျေးကွက်တွင် ဆယ်စုနှစ်တစ်ခုကျော် ကျွမ်းကျင်မှု' },
  'about.marketLeader': { en: 'Market Leadership', mm: 'စျေးကွက်ခေါင်းဆောင်မှု' },
  'about.marketLeaderDesc': { en: 'Trusted by thousands for buying, selling, and investing in properties', mm: 'အိမ်ခြံမြေ ဝယ်ယူခြင်း၊ ရောင်းချခြင်းနှင့် ရင်းနှီးမြှုပ်နှံခြင်းတွင် လူထောင်ပေါင်းများစွာမှ ယုံကြည်ခံရသော' },
  'about.innovation': { en: 'Innovation Focus', mm: 'ဆန်းသစ်တီထွင်မှု အာရုံစိုက်မှု' },
  'about.innovationDesc': { en: 'Leveraging cutting-edge technology to enhance your property journey', mm: 'သင်၏ အိမ်ခြံမြေခရီးကို မြှင့်တင်ရန် အဆင့်မြင့် နည်းပညာကို အသုံးပြုခြင်း' },
  
  // Carousel
  'carousel.villa': { en: 'Modern Luxury Villa', mm: 'ခေတ်မီဇိမ်ခံ အိမ်ကြီး' },
  'carousel.villaDesc': { en: 'Stunning contemporary architecture with premium amenities', mm: 'အဆင့်မြင့် အဆောက်အအုံနှင့် ထူးခြားလှပသော ခေတ်မီဗိသုကာ' },
  'carousel.apartment': { en: 'Urban Apartment', mm: 'မြို့တွင်း တိုက်ခန်း' },
  'carousel.apartmentDesc': { en: 'City living at its finest with modern conveniences', mm: 'ခေတ်မီအဆင်ပြေမှုများဖြင့် မြို့တွင်းနေထိုင်မှု အကောင်းဆုံး' },
  'carousel.office': { en: 'Commercial Office Space', mm: 'စီးပွားရေး ရုံးခန်း' },
  'carousel.officeDesc': { en: 'Prime business location for your success', mm: 'သင်၏အောင်မြင်မှုအတွက် အကောင်းဆုံး စီးပွားရေးတည်နေရာ' },
  'carousel.estate': { en: 'Luxury Estate with Pool', mm: 'ရေကူးကန်ပါ ဇိမ်ခံအိမ်' },
  'carousel.estateDesc': { en: 'Resort-style living with exclusive amenities', mm: 'သီးသန့် အဆောက်အအုံများဖြင့် အပန်းဖြေစခန်းပုံစံ နေထိုင်မှု' },
  'carousel.condo': { en: 'Downtown Condominium', mm: 'မြို့လယ်ခေါင် ကွန်ဒို' },
  'carousel.condoDesc': { en: 'Modern urban lifestyle in the heart of the city', mm: 'မြို့၏ နှလုံးသားတွင် ခေတ်မီမြို့ပြဘဝပုံစံ' },
  'carousel.scrollDown': { en: 'Scroll Down', mm: 'အောက်သို့ဆွဲကြည့်ရန်' },
  
  // Companies
  'companies.title': { en: 'Real Estate Companies', mm: 'အိမ်ခြံမြေကုမ္ပဏီများ' },
  'companies.subtitle': { en: 'Browse verified property companies', mm: 'အတည်ပြုထားသော အိမ်ခြံမြေကုမ္ပဏီများကို ကြည့်ရှုပါ' },
  'companies.search': { en: 'Search companies...', mm: 'ကုမ္ပဏီများရှာဖွေရန်...' },
  'companies.verified': { en: 'Verified', mm: 'အတည်ပြုပြီး' },
  'companies.properties': { en: 'properties', mm: 'အိမ်ခြံမြေများ' },
  'companies.viewProperties': { en: 'View Properties', mm: 'အိမ်ခြံမြေများကြည့်ရန်' },
  'companies.contact': { en: 'Contact', mm: 'ဆက်သွယ်ရန်' },
  'companies.noResults': { en: 'No Companies Found', mm: 'ကုမ္ပဏီများမတွေ့ပါ' },
  'companies.noResultsDesc': { en: 'Try adjusting your search criteria', mm: 'သင့်ရှာဖွေမှုစံနှုန်းများကို ပြင်ဆင်ကြည့်ပါ' },
  'companies.categories.all': { en: 'All Categories', mm: 'အမျိုးအစားအားလုံး' },
  'companies.categories.luxury': { en: 'Luxury Properties', mm: 'ဇိမ်ခံအိမ်ခြံမြေများ' },
  'companies.categories.ecoFriendly': { en: 'Eco-Friendly', mm: 'ဂေဟစနစ်နှင့်သဟဇာတဖြစ်သော' },

  // Forms
  'forms.name': { en: 'Name', mm: 'အမည်' },
  'forms.email': { en: 'Email', mm: 'အီးမေးလ်' },
  'forms.phone': { en: 'Phone', mm: 'ဖုန်း' },
  'forms.message': { en: 'Message', mm: 'မက်ဆေ့ဂ်' },
  'forms.subject': { en: 'Subject', mm: 'ခေါင်းစဉ်' },
  'forms.category': { en: 'Category', mm: 'အမျိုးအစား' },
  'forms.search': { en: 'Search', mm: 'ရှာဖွေရန်' },
  'forms.searchPlaceholder': { en: 'Search...', mm: 'ရှာဖွေရန်...' },
  'forms.submit': { en: 'Submit', mm: 'တင်သွင်းရန်' },
  'forms.sending': { en: 'Sending...', mm: 'ပို့နေသည်...' },
  'forms.required': { en: 'Required', mm: 'လိုအပ်သည်' },
  'forms.optional': { en: 'Optional', mm: 'ရွေးချယ်နိုင်သည်' },
  'forms.clear': { en: 'Clear', mm: 'ရှင်းလင်းရန်' },
  'forms.reset': { en: 'Reset', mm: 'ပြန်လည်စတင်ရန်' },
  'forms.cancel': { en: 'Cancel', mm: 'ပယ်ဖျက်ရန်' },
  'forms.save': { en: 'Save', mm: 'သိမ်းဆည်းရန်' },
  'forms.edit': { en: 'Edit', mm: 'တည်းဖြတ်ရန်' },
  'forms.delete': { en: 'Delete', mm: 'ဖျက်ရန်' },
  'forms.confirm': { en: 'Confirm', mm: 'အတည်ပြုရန်' },
  'forms.yes': { en: 'Yes', mm: 'ဟုတ်ကဲ့' },
  'forms.no': { en: 'No', mm: 'မဟုတ်ပါ' },
  'forms.loading': { en: 'Loading...', mm: 'တည်ဆောက်နေသည်...' },
  'forms.loadMore': { en: 'Load More', mm: 'ပိုမိုတင်ရန်' },
  'forms.error': { en: 'Error', mm: 'အမှား' },
  'forms.success': { en: 'Success', mm: 'အောင်မြင်ပါပြီ' },
  'forms.warning': { en: 'Warning', mm: 'သတိပေးချက်' },
  'forms.info': { en: 'Information', mm: 'အချက်အလက်' },

  // Contact Form
  'contact.title': { en: 'Contact Us', mm: 'ဆက်သွယ်ရန်' },
  'contact.subtitle': { en: 'Get in touch with our team', mm: 'ကျွန်ုပ်တို့၏အဖွဲ့နှင့်ဆက်သွယ်ပါ' },
  'contact.nameLabel': { en: 'Full Name', mm: 'အမည်အပြည့်အစုံ' },
  'contact.namePlaceholder': { en: 'Enter your full name', mm: 'သင့်အမည်အပြည့်အစုံကိုရိုက်ထည့်ပါ' },
  'contact.emailLabel': { en: 'Email Address', mm: 'အီးမေးလ်လိပ်စာ' },
  'contact.emailPlaceholder': { en: 'Enter your email address', mm: 'သင့်အီးမေးလ်လိပ်စာကိုရိုက်ထည့်ပါ' },
  'contact.phoneLabel': { en: 'Phone Number', mm: 'ဖုန်းနံပါတ်' },
  'contact.phonePlaceholder': { en: 'Enter your phone number', mm: 'သင့်ဖုန်းနံပါတ်ကိုရိုက်ထည့်ပါ' },
  'contact.categoryLabel': { en: 'Inquiry Category', mm: 'မေးမြန်းမှုအမျိုးအစား' },
  'contact.categoryPlaceholder': { en: 'Select a category', mm: 'အမျိုးအစားတစ်ခုရွေးချယ်ပါ' },
  'contact.messageLabel': { en: 'Message', mm: 'မက်ဆေ့ဂ်' },
  'contact.messagePlaceholder': { en: 'Tell us how we can help you...', mm: 'ကျွန်ုပ်တို့ဘယ်လိုကူညီနိုင်မလဲပြောပြပါ...' },
  'contact.submitButton': { en: 'Send Message', mm: 'မက်ဆေ့ဂ်ပို့ရန်' },
  'contact.successTitle': { en: 'Message Sent Successfully!', mm: 'မက်ဆေ့ဂ်အောင်မြင်စွာပို့ပြီးပါပြီ!' },
  'contact.successMessage': { en: 'Thank you for contacting us! Your message has been sent successfully. Our team will review your inquiry and get back to you within 24 hours.', mm: 'ကျွန်ုပ်တို့နှင့်ဆက်သွယ်ပေးသည့်အတွက်ကျေးဇူးတင်ပါသည်! သင့်မက်ဆေ့ဂ်ကိုအောင်မြင်စွာပို့ပြီးပါပြီ။ ကျွန်ုပ်တို့၏အဖွဲ့သည် သင့်မေးမြန်းမှုကိုစစ်ဆေးပြီး 24 နာရီအတွင်းပြန်လည်ဆက်သွယ်ပေးပါမည်။' },
  'contact.errorTitle': { en: 'Unable to Send Message', mm: 'မက်ဆေ့ဂ်ပို့၍မရပါ' },
  'contact.errorMessage': { en: 'We encountered an issue while sending your message. Please check your information and try again.', mm: 'သင့်မက်ဆေ့ဂ်ပို့စဉ်တွင် ပြဿနာတစ်ခုကြုံတွေ့ခဲ့ပါသည်။ သင့်အချက်အလက်များကိုစစ်ဆေးပြီး ပြန်လည်ကြိုးစားကြည့်ပါ။' },

  // Search Forms
  'search.searchPlaceholder': { en: 'Search properties...', mm: 'အိမ်ခြံမြေများရှာဖွေရန်...' },
  'search.searchKnowledge': { en: 'Search knowledge...', mm: 'အသိပညာရှာဖွေရန်...' },
  'search.searchFAQ': { en: 'Search FAQ...', mm: 'မေးခွန်းများရှာဖွေရန်...' },
  'search.noResults': { en: 'No results found', mm: 'ရလဒ်များမတွေ့ပါ' },
  'search.tryAgain': { en: 'Try different keywords', mm: 'အခြားသော့ချက်စာလုံးများကြိုးစားကြည့်ပါ' },

  // FAQ
  'faq.title': { en: 'Frequently Asked Questions', mm: 'မကြာခဏမေးလေ့ရှိသောမေးခွန်းများ' },
  'faq.subtitle': { en: 'Find answers to common questions', mm: 'အများအားဖြင့်မေးလေ့ရှိသောမေးခွန်းများ၏အဖြေများကိုရှာဖွေပါ' },
  'faq.searchPlaceholder': { en: 'Search questions...', mm: 'မေးခွန်းများရှာဖွေရန်...' },
  'faq.noResults': { en: 'No questions found', mm: 'မေးခွန်းများမတွေ့ပါ' },
  'faq.tryAgain': { en: 'Try different search terms', mm: 'အခြားရှာဖွေမှုစာလုံးများကြိုးစားကြည့်ပါ' },

  // Knowledge Hub
  'knowledge.title': { en: 'Knowledge Hub', mm: 'အသိပညာဗဟို' },
  'knowledge.subtitle': { en: 'Learn about real estate', mm: 'အိမ်ခြံမြေအကြောင်းလေ့လာပါ' },
  'knowledge.searchPlaceholder': { en: 'Search articles...', mm: 'ဆောင်းပါးများရှာဖွေရန်...' },
  'knowledge.categoryAll': { en: 'All Categories', mm: 'အမျိုးအစားအားလုံး' },
  'knowledge.readMore': { en: 'Read More', mm: 'အသေးစိတ်ကြည့်ရန်' },
  'knowledge.minRead': { en: 'min read', mm: 'မိနစ်ဖတ်ရန်' },
  'knowledge.views': { en: 'views', mm: 'ကြည့်ရှုမှုများ' },
  'knowledge.by': { en: 'by', mm: 'မှ' },

  // News & Updates
  'news.title': { en: 'News & Updates', mm: 'သတင်းနှင့်အပ်ဒိတ်များ' },
  'news.subtitle': { en: 'Stay informed with the latest real estate news', mm: 'နောက်ဆုံးအိမ်ခြံမြေသတင်းများနှင့်အတူ အသိပေးထားပါ' },
  'news.searchPlaceholder': { en: 'Search news...', mm: 'သတင်းများရှာဖွေရန်...' },
  'news.categoryAll': { en: 'All Categories', mm: 'အမျိုးအစားအားလုံး' },
  'news.readMore': { en: 'Read More', mm: 'အသေးစိတ်ကြည့်ရန်' },
  'news.minRead': { en: 'min read', mm: 'မိနစ်ဖတ်ရန်' },
  'news.views': { en: 'views', mm: 'ကြည့်ရှုမှုများ' },
  'news.by': { en: 'by', mm: 'မှ' },
  'news.noResults': { en: 'No news found', mm: 'သတင်းများမတွေ့ပါ' },
  'news.tryAgain': { en: 'Try different search terms', mm: 'အခြားရှာဖွေမှုစာလုံးများကြိုးစားကြည့်ပါ' },
  'news.loading': { en: 'Loading news...', mm: 'သတင်းများတည်ဆောက်နေသည်...' },
  'news.loadMore': { en: 'Load More', mm: 'ပိုမိုတင်ရန်' },
  'news.typeMore': { en: 'Type at least 3 characters', mm: 'အနည်းဆုံး ၃ လုံးရိုက်ပါ' },
  'news.typeMoreDesc': { en: 'Search will start when you type more characters', mm: 'ပိုမိုရိုက်သောအခါ ရှာဖွေမှုစတင်မည်' },
  'news.error': { en: 'Failed to load news', mm: 'သတင်းများတည်ဆောက်၍မရပါ' },
  
  // Common
  'common.back': { en: 'Back', mm: 'ပြန်သွားရန်' },
  
  // Calculator
  'calculator.title': { en: 'Property Calculator', mm: 'အိမ်ခြံမြေတွက်ချက်စက်' },
  'calculator.subtitle': { en: 'Calculate your mortgage payments and plan your property investment', mm: 'သင့်အိမ်ခြံမြေငွေချေးမှုနှင့်ရင်းနှီးမြှုပ်နှံမှုကိုတွက်ချက်ပါ' },
  'calculator.description': { en: 'Calculate mortgage payments and property investment returns', mm: 'အိမ်ခြံမြေငွေချေးမှုနှင့်ရင်းနှီးမြှုပ်နှံမှုအမြတ်ကိုတွက်ချက်ပါ' },
  'calculator.keywords': { en: 'property calculator, mortgage calculator, real estate calculator', mm: 'အိမ်ခြံမြေတွက်ချက်စက်, ငွေချေးတွက်ချက်စက်' },
  'calculator.inputDetails': { en: 'Input Details', mm: 'အချက်အလက်များထည့်သွင်းရန်' },
  'calculator.propertyValue': { en: 'Property Value', mm: 'အိမ်ခြံမြေတန်ဖိုး' },
  'calculator.downPayment': { en: 'Down Payment', mm: 'ကြိုတင်ပေးချေမှု' },
  'calculator.loanTerm': { en: 'Loan Term', mm: 'ငွေချေးကာလ' },
  'calculator.interestRate': { en: 'Interest Rate', mm: 'အတိုးနှုန်း' },
  'calculator.years': { en: 'Years', mm: 'နှစ်' },
  'calculator.reset': { en: 'Reset', mm: 'ပြန်စရန်' },
  'calculator.calculate': { en: 'Calculate', mm: 'တွက်ချက်ရန်' },
  'calculator.results': { en: 'Calculation Results', mm: 'တွက်ချက်မှုရလဒ်များ' },
  'calculator.loanAmount': { en: 'Loan Amount', mm: 'ငွေချေးပမာဏ' },
  'calculator.monthlyPayment': { en: 'Monthly Payment', mm: 'လစဉ်ပေးချေမှု' },
  'calculator.totalPayment': { en: 'Total Payment', mm: 'စုစုပေါင်းပေးချေမှု' },
  'calculator.totalInterest': { en: 'Total Interest', mm: 'စုစုပေါင်းအတိုး' },
  'calculator.infoTitle': { en: 'Important Note', mm: 'အရေးကြီးသောမှတ်ချက်' },
  'calculator.infoText': { en: 'This calculation is for estimation purposes only. Actual rates may vary based on your credit score and other factors.', mm: 'ဤတွက်ချက်မှုသည် ခန့်မှန်းရည်ရွယ်ချက်အတွက်သာဖြစ်သည်။ အတည်ပြုနှုန်းများသည် သင့်အကြွေးအမှတ်နှင့်အခြားအချက်များပေါ်မူတည်၍ ကွဲပြားနိုင်သည်။' },
  'calculator.benefit1.title': { en: 'Accurate Calculations', mm: 'တိကျသောတွက်ချက်မှု' },
  'calculator.benefit1.description': { en: 'Get precise mortgage payment calculations', mm: 'တိကျသောငွေချေးပေးချေမှုတွက်ချက်မှုများရယူပါ' },
  'calculator.benefit2.title': { en: 'Easy to Use', mm: 'အသုံးပြုရလွယ်ကူ' },
  'calculator.benefit2.description': { en: 'Simple interface for quick calculations', mm: 'မြန်ဆန်သောတွက်ချက်မှုအတွက် ရိုးရှင်းသောစနစ်' },
  'calculator.benefit3.title': { en: 'Investment Planning', mm: 'ရင်းနှီးမြှုပ်နှံမှုစီစဉ်ခြင်း' },
  'calculator.benefit3.description': { en: 'Plan your property investment wisely', mm: 'သင့်အိမ်ခြံမြေရင်းနှီးမြှုပ်နှံမှုကို ပညာရှိစွာစီစဉ်ပါ' },
  
  // Yar Pyat Tax Calculator specific translations
  'calculator.yarPyat.title': { en: 'Yar Pyat Tax Calculator', mm: 'ရာပြတ်ခွန် တွက်ချက်ရေးစနစ်' },
  'calculator.yarPyat.subtitle': { en: 'Calculate property taxes for land transactions in Myanmar', mm: 'မြန်မာနိုင်ငံရှိ မြေကွက်ရောင်းဝယ်မှုများအတွက် အိမ်ခြံမြေအခွန်များကို တွက်ချက်ပါ' },
  'calculator.yarPyat.locationSelection': { en: 'Location Selection', mm: 'တည်နေရာရွေးချယ်ရန်' },
  'calculator.yarPyat.locationDescription': { en: 'Select Region, City, Ward, and Road to get the property rate', mm: 'အိမ်ခြံမြေနှုန်းထားရရှိရန် တိုင်းဒေသကြီး၊ မြို့၊ ရပ်ကွက်နှင့် လမ်းကို ရွေးချယ်ပါ' },
  'calculator.yarPyat.region': { en: 'Region', mm: 'တိုင်းဒေသကြီး / ပြည်နယ်' },
  'calculator.yarPyat.city': { en: 'City', mm: 'မြို့' },
  'calculator.yarPyat.ward': { en: 'Ward', mm: 'ရပ်ကွက်' },
  'calculator.yarPyat.road': { en: 'Road', mm: 'လမ်း' },
  'calculator.yarPyat.landArea': { en: 'Land Area', mm: 'မြေကွက်အကျယ်အဝန်း' },
  'calculator.yarPyat.landAreaDescription': { en: 'Enter the total land area in square feet', mm: 'စတုရန်းပေဖြင့် မြေကွက်၏ စုစုပေါင်းဧရိယာကို ထည့်သွင်းပါ' },
  'calculator.yarPyat.landAreaSqft': { en: 'Land Area (Sqft)', mm: 'စတုရန်းပေ' },
  'calculator.yarPyat.length': { en: 'Length (ft)', mm: 'အလျား (ပေ)' },
  'calculator.yarPyat.width': { en: 'Width (ft)', mm: 'အနံ (ပေ)' },
  'calculator.yarPyat.or': { en: 'OR', mm: 'သို့မဟုတ်' },
  'calculator.yarPyat.landAreaExample': { en: 'Example: If land is 40 ft × 60 ft = 2,400 Sqft', mm: 'ဥပမာ: မြေကွက်သည် 40 ပေ × 60 ပေ = 2,400 စတုရန်းပေ' },
  'calculator.yarPyat.ratePerSqft': { en: 'Rate per Sqft', mm: 'ရာပြတ်တန်ဖိုး' },
  'calculator.yarPyat.calculateTax': { en: 'Calculate Tax', mm: 'အခွန်တွက်ချက်ရန်' },
  'calculator.yarPyat.taxResults': { en: 'Tax Calculation Results', mm: 'တွက်ချက်မှုရလဒ်များ' },
  'calculator.yarPyat.location': { en: 'Location:', mm: 'တည်နေရာ:' },
  'calculator.yarPyat.assessedValue': { en: 'Assessed Value', mm: 'အခွန်တန်ဖိုး' },
  'calculator.yarPyat.sellingTax': { en: 'Selling Tax (10%)', mm: 'ရောင်းခွန် (10%)' },
  'calculator.yarPyat.buyingTax': { en: 'Buying Tax (7.5%)', mm: 'ဝယ်ခွန် (7.5%)' },
  'calculator.yarPyat.fillFormMessage': { en: 'Fill in the form and click "Calculate Tax" to see results', mm: 'ပုံစံကိုဖြည့်ပြီး ရလဒ်များကိုကြည့်ရန် "အခွန်တွက်ချက်ရန်" ကိုနှိပ်ပါ' },
  'calculator.yarPyat.infoNote': { en: 'These calculations are estimates based on standard rates. Actual taxes may vary. Please consult with local authorities for exact amounts.', mm: 'ဤတွက်ချက်မှုများသည် စံနှုန်းများအပေါ်အခြေခံသော ခန့်မှန်းချက်များဖြစ်သည်။ အတည်ပြုအခွန်များသည် ကွဲပြားနိုင်သည်။ တိကျသောပမာဏများအတွက် ဒေသဆိုင်ရာအာဏာပိုင်များနှင့် တိုင်ပင်ပါ။' },
  
  // Missing YarPyat calculator translations
  'calculator.yarPyat.township': { en: 'Township', mm: 'မြို့နယ်' },
  'calculator.yarPyat.selectRegion': { en: 'Select Region', mm: 'တိုင်းဒေသကြီးရွေးချယ်ရန်' },
  'calculator.yarPyat.selectTownship': { en: 'Select Township', mm: 'မြို့နယ်ရွေးချယ်ရန်' },
  'calculator.yarPyat.selectWard': { en: 'Select Ward', mm: 'ရပ်ကွက်ရွေးချယ်ရန်' },
  'calculator.yarPyat.selectRoad': { en: 'Select Road', mm: 'လမ်းရွေးချယ်ရန်' },
  'calculator.yarPyat.areaInSqft': { en: 'Area in Sqft', mm: 'စတုရန်းပေဖြင့်ဧရိယာ' },
  'calculator.yarPyat.calculate': { en: 'Calculate', mm: 'တွက်ချက်ရန်' },
  'calculator.yarPyat.reset': { en: 'Reset', mm: 'ပြန်စရန်' },
  'calculator.yarPyat.taxCalculationResults': { en: 'Tax Calculation Results', mm: 'အခွန်တွက်ချက်မှုရလဒ်များ' },
  'calculator.yarPyat.resultsDescription': { en: 'Your tax calculation results', mm: 'သင့်အခွန်တွက်ချက်မှုရလဒ်များ' },
  'calculator.yarPyat.totalTax': { en: 'Total Tax', mm: 'စုစုပေါင်းအခွန်' },
  'calculator.yarPyat.selectLocationAndArea': { en: 'Select location and enter land area to calculate taxes', mm: 'အခွန်တွက်ချက်ရန် တည်နေရာရွေးချယ်ပြီး မြေကွက်ဧရိယာထည့်သွင်းပါ' },
  
  // Additional YarPyat calculator translations
  'calculator.yarPyat.selectAllFields': { en: 'Please select Region, City, Ward, and Road', mm: 'တိုင်းဒေသကြီး၊ မြို့၊ ရပ်ကွက်နှင့် လမ်းကို ရွေးချယ်ပါ' },
  'calculator.yarPyat.enterValidArea': { en: 'Please enter a valid land area', mm: 'မြေကွက်ဧရိယာကို မှန်ကန်စွာ ထည့်သွင်းပါ' },
  'calculator.yarPyat.enterLengthAndWidth': { en: 'Please enter both length and width', mm: 'အလျားနှင့် အနံကို ထည့်သွင်းပါ' },
  'calculator.yarPyat.autoCalculated': { en: 'Auto-calculated from length × width', mm: 'အလျား × အနံမှ အလိုအလျောက်တွက်ချက်သည်' },
  
  // SignIn Page
  'signin.title': { en: 'Sign In', mm: 'ဝင်ရောက်ရန်' },
  'signin.subtitle': { en: 'Welcome back to Jade Property', mm: 'Jade Property သို့ပြန်လည်ကြိုဆိုပါသည်' },
  'signin.email': { en: 'Email', mm: 'အီးမေးလ်' },
  'signin.phone': { en: 'Phone', mm: 'ဖုန်း' },
  'signin.phoneNumber': { en: 'Phone Number', mm: 'ဖုန်းနံပါတ်' },
  'signin.password': { en: 'Password', mm: 'စကားဝှက်' },
  'signin.signIn': { en: 'Sign In', mm: 'ဝင်ရောက်ရန်' },
  'signin.signingIn': { en: 'Signing in...', mm: 'ဝင်ရောက်နေသည်...' },
  'signin.or': { en: 'Or', mm: 'သို့မဟုတ်' },
  'signin.continueAsGuest': { en: 'Continue as Guest', mm: 'ဧည့်သည်အနေဖြင့်ဆက်လက်ရန်' },
  'signin.noAccount': { en: "Don't have an account?", mm: 'အကောင့်မရှိသေးပါသလား?' },
  'signin.signUp': { en: 'Sign Up', mm: 'စာရင်းသွင်းရန်' },
  'signin.emailPlaceholder': { en: 'you@example.com', mm: 'you@example.com' },
  'signin.welcomeBack': { en: 'Welcome back!', mm: 'ပြန်လည်ကြိုဆိုပါသည်!' },
  'signin.signInSuccessful': { en: 'Sign in successful', mm: 'အောင်မြင်စွာဝင်ရောက်ပါပြီ' },
  'signin.signInFailed': { en: 'Sign in failed. Please try again.', mm: 'ဝင်ရောက်မှုမအောင်မြင်ပါ။ ကျေးဇူးပြု၍ထပ်ကြိုးစားပါ။' },
  'signin.invalidPhonePassword': { en: 'Invalid phone number or password. Please try again.', mm: 'ဖုန်းနံပါတ်သို့မဟုတ်စကားဝှက်မမှန်ပါ။ ကျေးဇူးပြု၍ထပ်ကြိုးစားပါ။' },
  'signin.phoneValidationError': { en: 'Phone number must have 9 digits.', mm: 'ဖုန်းနံပါတ်သည် 9 လုံးရှိရပါမည်။' },
  'signin.guestAccess': { en: 'Guest Access', mm: 'ဧည့်သည်ဝင်ရောက်မှု' },
  'signin.guestMessage': { en: 'Signed in as guest. Some features may be limited.', mm: 'ဧည့်သည်အနေဖြင့်ဝင်ရောက်ပါပြီ။ အချို့အင်္ဂါရပ်များကန့်သတ်ထားနိုင်ပါသည်။' },

  // Common translations
  'common.loading': { en: 'Loading...', mm: 'ဖွင့်နေသည်...' },
  'common.error': { en: 'Error', mm: 'အမှား' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const translation = translations[key];
    if (!translation) {
      console.warn(`Translation key not found: ${key}`);
      return key;
    }
    return translation[language];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}